// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CloudhsmCloudhsmsClientsCreate invokes cloudhsm_cloudhsms_clients_create operation.
	//
	// POST /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients
	CloudhsmCloudhsmsClientsCreate(ctx context.Context, request *WrappedCreateCloudHSMClient, params CloudhsmCloudhsmsClientsCreateParams) (*WrappedCreateCloudHSMClient, error)
	// CloudhsmCloudhsmsClientsDestroy invokes cloudhsm_cloudhsms_clients_destroy operation.
	//
	// DELETE /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}
	CloudhsmCloudhsmsClientsDestroy(ctx context.Context, params CloudhsmCloudhsmsClientsDestroyParams) error
	// CloudhsmCloudhsmsClientsList invokes cloudhsm_cloudhsms_clients_list operation.
	//
	// GET /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients
	CloudhsmCloudhsmsClientsList(ctx context.Context, params CloudhsmCloudhsmsClientsListParams) (*PaginatedCloudHSMClientList, error)
	// CloudhsmCloudhsmsClientsRetrieve invokes cloudhsm_cloudhsms_clients_retrieve operation.
	//
	// GET /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}
	CloudhsmCloudhsmsClientsRetrieve(ctx context.Context, params CloudhsmCloudhsmsClientsRetrieveParams) (*WrappedCloudHSMClient, error)
	// CloudhsmCloudhsmsClientsUpdate invokes cloudhsm_cloudhsms_clients_update operation.
	//
	// PUT /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}
	CloudhsmCloudhsmsClientsUpdate(ctx context.Context, request *WrappedCloudHSMClient, params CloudhsmCloudhsmsClientsUpdateParams) (*WrappedCloudHSMClient, error)
	// CloudhsmCloudhsmsCreate invokes cloudhsm_cloudhsms_create operation.
	//
	// POST /cloudhsm/cloudhsms
	CloudhsmCloudhsmsCreate(ctx context.Context, request *WrappedCreateCloudHSM) (*WrappedCreateCloudHSM, error)
	// CloudhsmCloudhsmsDestroy invokes cloudhsm_cloudhsms_destroy operation.
	//
	// DELETE /cloudhsm/cloudhsms/{resource_id}
	CloudhsmCloudhsmsDestroy(ctx context.Context, params CloudhsmCloudhsmsDestroyParams) error
	// CloudhsmCloudhsmsList invokes cloudhsm_cloudhsms_list operation.
	//
	// GET /cloudhsm/cloudhsms
	CloudhsmCloudhsmsList(ctx context.Context) (*PaginatedCloudHSMList, error)
	// CloudhsmCloudhsmsPeersCreate invokes cloudhsm_cloudhsms_peers_create operation.
	//
	// POST /cloudhsm/cloudhsms/{resource_id}/peers
	CloudhsmCloudhsmsPeersCreate(ctx context.Context, request *WrappedCreateCloudHSMPeer, params CloudhsmCloudhsmsPeersCreateParams) (*WrappedCloudHSMPeer, error)
	// CloudhsmCloudhsmsPeersDestroy invokes cloudhsm_cloudhsms_peers_destroy operation.
	//
	// DELETE /cloudhsm/cloudhsms/{resource_id}/peers/{peer_id}
	CloudhsmCloudhsmsPeersDestroy(ctx context.Context, params CloudhsmCloudhsmsPeersDestroyParams) error
	// CloudhsmCloudhsmsPeersRetrieve invokes cloudhsm_cloudhsms_peers_retrieve operation.
	//
	// GET /cloudhsm/cloudhsms/{resource_id}/peers
	CloudhsmCloudhsmsPeersRetrieve(ctx context.Context, params CloudhsmCloudhsmsPeersRetrieveParams) (*CloudHSMPeerList, error)
	// CloudhsmCloudhsmsRetrieve invokes cloudhsm_cloudhsms_retrieve operation.
	//
	// GET /cloudhsm/cloudhsms/{resource_id}
	CloudhsmCloudhsmsRetrieve(ctx context.Context, params CloudhsmCloudhsmsRetrieveParams) (*WrappedCloudHSM, error)
	// CloudhsmCloudhsmsUpdate invokes cloudhsm_cloudhsms_update operation.
	//
	// PUT /cloudhsm/cloudhsms/{resource_id}
	CloudhsmCloudhsmsUpdate(ctx context.Context, request *WrappedCloudHSM, params CloudhsmCloudhsmsUpdateParams) (*WrappedCloudHSM, error)
	// CloudhsmLicensesCreate invokes cloudhsm_licenses_create operation.
	//
	// POST /cloudhsm/licenses
	CloudhsmLicensesCreate(ctx context.Context, request *WrappedCreateCloudHSMSoftwareLicense) (*WrappedCreateCloudHSMSoftwareLicense, error)
	// CloudhsmLicensesDestroy invokes cloudhsm_licenses_destroy operation.
	//
	// DELETE /cloudhsm/licenses/{resource_id}
	CloudhsmLicensesDestroy(ctx context.Context, params CloudhsmLicensesDestroyParams) error
	// CloudhsmLicensesList invokes cloudhsm_licenses_list operation.
	//
	// GET /cloudhsm/licenses
	CloudhsmLicensesList(ctx context.Context) (*PaginatedCloudHSMSoftwareLicenseList, error)
	// CloudhsmLicensesRetrieve invokes cloudhsm_licenses_retrieve operation.
	//
	// GET /cloudhsm/licenses/{resource_id}
	CloudhsmLicensesRetrieve(ctx context.Context, params CloudhsmLicensesRetrieveParams) (*WrappedCloudHSMSoftwareLicense, error)
	// CloudhsmLicensesUpdate invokes cloudhsm_licenses_update operation.
	//
	// PUT /cloudhsm/licenses/{resource_id}
	CloudhsmLicensesUpdate(ctx context.Context, request *WrappedCloudHSMSoftwareLicense, params CloudhsmLicensesUpdateParams) (*WrappedCloudHSMSoftwareLicense, error)
	// KmsKeysCreate invokes kms_keys_create operation.
	//
	// POST /kms/keys
	KmsKeysCreate(ctx context.Context, request *WrappedCreateKey) (*WrappedCreateKey, error)
	// KmsKeysDecrypt invokes kms_keys_decrypt operation.
	//
	// POST /kms/keys/{resource_id}/decrypt
	KmsKeysDecrypt(ctx context.Context, request *WrappedKeyCipher, params KmsKeysDecryptParams) (*WrappedKeyPlain, error)
	// KmsKeysDestroy invokes kms_keys_destroy operation.
	//
	// DELETE /kms/keys/{resource_id}
	KmsKeysDestroy(ctx context.Context, params KmsKeysDestroyParams) error
	// KmsKeysEncrypt invokes kms_keys_encrypt operation.
	//
	// POST /kms/keys/{resource_id}/encrypt
	KmsKeysEncrypt(ctx context.Context, request *WrappedKeyPlain, params KmsKeysEncryptParams) (*WrappedKeyCipher, error)
	// KmsKeysList invokes kms_keys_list operation.
	//
	// GET /kms/keys
	KmsKeysList(ctx context.Context) (*PaginatedKeyList, error)
	// KmsKeysRetrieve invokes kms_keys_retrieve operation.
	//
	// GET /kms/keys/{resource_id}
	KmsKeysRetrieve(ctx context.Context, params KmsKeysRetrieveParams) (*WrappedKey, error)
	// KmsKeysRotate invokes kms_keys_rotate operation.
	//
	// POST /kms/keys/{resource_id}/rotate
	KmsKeysRotate(ctx context.Context, params KmsKeysRotateParams) (KmsKeysRotateRes, error)
	// KmsKeysScheduleDestruction invokes kms_keys_schedule_destruction operation.
	//
	// POST /kms/keys/{resource_id}/schedule-destruction
	KmsKeysScheduleDestruction(ctx context.Context, request *WrappedScheduleDestructionKey, params KmsKeysScheduleDestructionParams) error
	// KmsKeysStatus invokes kms_keys_status operation.
	//
	// POST /kms/keys/{resource_id}/status
	KmsKeysStatus(ctx context.Context, request *WrappedChangeKeyStatus, params KmsKeysStatusParams) error
	// KmsKeysUpdate invokes kms_keys_update operation.
	//
	// PUT /kms/keys/{resource_id}
	KmsKeysUpdate(ctx context.Context, request *WrappedKey, params KmsKeysUpdateParams) (*WrappedKey, error)
	// SecretmanagerVaultsCreate invokes secretmanager_vaults_create operation.
	//
	// POST /secretmanager/vaults
	SecretmanagerVaultsCreate(ctx context.Context, request *WrappedCreateVault) (*WrappedCreateVault, error)
	// SecretmanagerVaultsDestroy invokes secretmanager_vaults_destroy operation.
	//
	// DELETE /secretmanager/vaults/{resource_id}
	SecretmanagerVaultsDestroy(ctx context.Context, params SecretmanagerVaultsDestroyParams) error
	// SecretmanagerVaultsList invokes secretmanager_vaults_list operation.
	//
	// GET /secretmanager/vaults
	SecretmanagerVaultsList(ctx context.Context) (*PaginatedVaultList, error)
	// SecretmanagerVaultsRetrieve invokes secretmanager_vaults_retrieve operation.
	//
	// GET /secretmanager/vaults/{resource_id}
	SecretmanagerVaultsRetrieve(ctx context.Context, params SecretmanagerVaultsRetrieveParams) (*WrappedVault, error)
	// SecretmanagerVaultsSecretsCreate invokes secretmanager_vaults_secrets_create operation.
	//
	// POST /secretmanager/vaults/{vault_resource_id}/secrets
	SecretmanagerVaultsSecretsCreate(ctx context.Context, request *WrappedCreateSecret, params SecretmanagerVaultsSecretsCreateParams) (*WrappedCreateSecret, error)
	// SecretmanagerVaultsSecretsDestroy invokes secretmanager_vaults_secrets_destroy operation.
	//
	// DELETE /secretmanager/vaults/{vault_resource_id}/secrets
	SecretmanagerVaultsSecretsDestroy(ctx context.Context, request *WrappedDeleteSecret, params SecretmanagerVaultsSecretsDestroyParams) error
	// SecretmanagerVaultsSecretsList invokes secretmanager_vaults_secrets_list operation.
	//
	// GET /secretmanager/vaults/{vault_resource_id}/secrets
	SecretmanagerVaultsSecretsList(ctx context.Context, params SecretmanagerVaultsSecretsListParams) (*PaginatedSecretList, error)
	// SecretmanagerVaultsSecretsUnveil invokes secretmanager_vaults_secrets_unveil operation.
	//
	// POST /secretmanager/vaults/{vault_resource_id}/secrets/unveil
	SecretmanagerVaultsSecretsUnveil(ctx context.Context, request *WrappedUnvail, params SecretmanagerVaultsSecretsUnveilParams) (*WrappedUnvail, error)
	// SecretmanagerVaultsUpdate invokes secretmanager_vaults_update operation.
	//
	// PUT /secretmanager/vaults/{resource_id}
	SecretmanagerVaultsUpdate(ctx context.Context, request *WrappedVault, params SecretmanagerVaultsUpdateParams) (*WrappedVault, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CloudhsmCloudhsmsClientsCreate invokes cloudhsm_cloudhsms_clients_create operation.
//
// POST /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients
func (c *Client) CloudhsmCloudhsmsClientsCreate(ctx context.Context, request *WrappedCreateCloudHSMClient, params CloudhsmCloudhsmsClientsCreateParams) (*WrappedCreateCloudHSMClient, error) {
	res, err := c.sendCloudhsmCloudhsmsClientsCreate(ctx, request, params)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsClientsCreate(ctx context.Context, request *WrappedCreateCloudHSMClient, params CloudhsmCloudhsmsClientsCreateParams) (res *WrappedCreateCloudHSMClient, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "cloudhsm_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "cloudhsm_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CloudhsmResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/clients"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCloudhsmCloudhsmsClientsCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsClientsCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsClientsCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsClientsDestroy invokes cloudhsm_cloudhsms_clients_destroy operation.
//
// DELETE /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}
func (c *Client) CloudhsmCloudhsmsClientsDestroy(ctx context.Context, params CloudhsmCloudhsmsClientsDestroyParams) error {
	_, err := c.sendCloudhsmCloudhsmsClientsDestroy(ctx, params)
	return err
}

func (c *Client) sendCloudhsmCloudhsmsClientsDestroy(ctx context.Context, params CloudhsmCloudhsmsClientsDestroyParams) (res *CloudhsmCloudhsmsClientsDestroyNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "cloudhsm_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "cloudhsm_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CloudhsmResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/clients/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsClientsDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsClientsDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsClientsList invokes cloudhsm_cloudhsms_clients_list operation.
//
// GET /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients
func (c *Client) CloudhsmCloudhsmsClientsList(ctx context.Context, params CloudhsmCloudhsmsClientsListParams) (*PaginatedCloudHSMClientList, error) {
	res, err := c.sendCloudhsmCloudhsmsClientsList(ctx, params)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsClientsList(ctx context.Context, params CloudhsmCloudhsmsClientsListParams) (res *PaginatedCloudHSMClientList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "cloudhsm_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "cloudhsm_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CloudhsmResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/clients"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsClientsListOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsClientsListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsClientsRetrieve invokes cloudhsm_cloudhsms_clients_retrieve operation.
//
// GET /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}
func (c *Client) CloudhsmCloudhsmsClientsRetrieve(ctx context.Context, params CloudhsmCloudhsmsClientsRetrieveParams) (*WrappedCloudHSMClient, error) {
	res, err := c.sendCloudhsmCloudhsmsClientsRetrieve(ctx, params)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsClientsRetrieve(ctx context.Context, params CloudhsmCloudhsmsClientsRetrieveParams) (res *WrappedCloudHSMClient, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "cloudhsm_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "cloudhsm_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CloudhsmResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/clients/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsClientsRetrieveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsClientsRetrieveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsClientsUpdate invokes cloudhsm_cloudhsms_clients_update operation.
//
// PUT /cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}
func (c *Client) CloudhsmCloudhsmsClientsUpdate(ctx context.Context, request *WrappedCloudHSMClient, params CloudhsmCloudhsmsClientsUpdateParams) (*WrappedCloudHSMClient, error) {
	res, err := c.sendCloudhsmCloudhsmsClientsUpdate(ctx, request, params)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsClientsUpdate(ctx context.Context, request *WrappedCloudHSMClient, params CloudhsmCloudhsmsClientsUpdateParams) (res *WrappedCloudHSMClient, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "cloudhsm_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "cloudhsm_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CloudhsmResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/clients/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCloudhsmCloudhsmsClientsUpdateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsClientsUpdateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsClientsUpdateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsCreate invokes cloudhsm_cloudhsms_create operation.
//
// POST /cloudhsm/cloudhsms
func (c *Client) CloudhsmCloudhsmsCreate(ctx context.Context, request *WrappedCreateCloudHSM) (*WrappedCreateCloudHSM, error) {
	res, err := c.sendCloudhsmCloudhsmsCreate(ctx, request)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsCreate(ctx context.Context, request *WrappedCreateCloudHSM) (res *WrappedCreateCloudHSM, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/cloudhsm/cloudhsms"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCloudhsmCloudhsmsCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsDestroy invokes cloudhsm_cloudhsms_destroy operation.
//
// DELETE /cloudhsm/cloudhsms/{resource_id}
func (c *Client) CloudhsmCloudhsmsDestroy(ctx context.Context, params CloudhsmCloudhsmsDestroyParams) error {
	_, err := c.sendCloudhsmCloudhsmsDestroy(ctx, params)
	return err
}

func (c *Client) sendCloudhsmCloudhsmsDestroy(ctx context.Context, params CloudhsmCloudhsmsDestroyParams) (res *CloudhsmCloudhsmsDestroyNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsList invokes cloudhsm_cloudhsms_list operation.
//
// GET /cloudhsm/cloudhsms
func (c *Client) CloudhsmCloudhsmsList(ctx context.Context) (*PaginatedCloudHSMList, error) {
	res, err := c.sendCloudhsmCloudhsmsList(ctx)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsList(ctx context.Context) (res *PaginatedCloudHSMList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/cloudhsm/cloudhsms"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsListOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsPeersCreate invokes cloudhsm_cloudhsms_peers_create operation.
//
// POST /cloudhsm/cloudhsms/{resource_id}/peers
func (c *Client) CloudhsmCloudhsmsPeersCreate(ctx context.Context, request *WrappedCreateCloudHSMPeer, params CloudhsmCloudhsmsPeersCreateParams) (*WrappedCloudHSMPeer, error) {
	res, err := c.sendCloudhsmCloudhsmsPeersCreate(ctx, request, params)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsPeersCreate(ctx context.Context, request *WrappedCreateCloudHSMPeer, params CloudhsmCloudhsmsPeersCreateParams) (res *WrappedCloudHSMPeer, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/peers"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCloudhsmCloudhsmsPeersCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsPeersCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsPeersCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsPeersDestroy invokes cloudhsm_cloudhsms_peers_destroy operation.
//
// DELETE /cloudhsm/cloudhsms/{resource_id}/peers/{peer_id}
func (c *Client) CloudhsmCloudhsmsPeersDestroy(ctx context.Context, params CloudhsmCloudhsmsPeersDestroyParams) error {
	_, err := c.sendCloudhsmCloudhsmsPeersDestroy(ctx, params)
	return err
}

func (c *Client) sendCloudhsmCloudhsmsPeersDestroy(ctx context.Context, params CloudhsmCloudhsmsPeersDestroyParams) (res *CloudhsmCloudhsmsPeersDestroyNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/peers/"
	{
		// Encode "peer_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "peer_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.PeerID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsPeersDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsPeersDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsPeersRetrieve invokes cloudhsm_cloudhsms_peers_retrieve operation.
//
// GET /cloudhsm/cloudhsms/{resource_id}/peers
func (c *Client) CloudhsmCloudhsmsPeersRetrieve(ctx context.Context, params CloudhsmCloudhsmsPeersRetrieveParams) (*CloudHSMPeerList, error) {
	res, err := c.sendCloudhsmCloudhsmsPeersRetrieve(ctx, params)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsPeersRetrieve(ctx context.Context, params CloudhsmCloudhsmsPeersRetrieveParams) (res *CloudHSMPeerList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/peers"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsPeersRetrieveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsPeersRetrieveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsRetrieve invokes cloudhsm_cloudhsms_retrieve operation.
//
// GET /cloudhsm/cloudhsms/{resource_id}
func (c *Client) CloudhsmCloudhsmsRetrieve(ctx context.Context, params CloudhsmCloudhsmsRetrieveParams) (*WrappedCloudHSM, error) {
	res, err := c.sendCloudhsmCloudhsmsRetrieve(ctx, params)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsRetrieve(ctx context.Context, params CloudhsmCloudhsmsRetrieveParams) (res *WrappedCloudHSM, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsRetrieveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsRetrieveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmCloudhsmsUpdate invokes cloudhsm_cloudhsms_update operation.
//
// PUT /cloudhsm/cloudhsms/{resource_id}
func (c *Client) CloudhsmCloudhsmsUpdate(ctx context.Context, request *WrappedCloudHSM, params CloudhsmCloudhsmsUpdateParams) (*WrappedCloudHSM, error) {
	res, err := c.sendCloudhsmCloudhsmsUpdate(ctx, request, params)
	return res, err
}

func (c *Client) sendCloudhsmCloudhsmsUpdate(ctx context.Context, request *WrappedCloudHSM, params CloudhsmCloudhsmsUpdateParams) (res *WrappedCloudHSM, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/cloudhsm/cloudhsms/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCloudhsmCloudhsmsUpdateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmCloudhsmsUpdateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmCloudhsmsUpdateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmLicensesCreate invokes cloudhsm_licenses_create operation.
//
// POST /cloudhsm/licenses
func (c *Client) CloudhsmLicensesCreate(ctx context.Context, request *WrappedCreateCloudHSMSoftwareLicense) (*WrappedCreateCloudHSMSoftwareLicense, error) {
	res, err := c.sendCloudhsmLicensesCreate(ctx, request)
	return res, err
}

func (c *Client) sendCloudhsmLicensesCreate(ctx context.Context, request *WrappedCreateCloudHSMSoftwareLicense) (res *WrappedCreateCloudHSMSoftwareLicense, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/cloudhsm/licenses"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCloudhsmLicensesCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmLicensesCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmLicensesCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmLicensesDestroy invokes cloudhsm_licenses_destroy operation.
//
// DELETE /cloudhsm/licenses/{resource_id}
func (c *Client) CloudhsmLicensesDestroy(ctx context.Context, params CloudhsmLicensesDestroyParams) error {
	_, err := c.sendCloudhsmLicensesDestroy(ctx, params)
	return err
}

func (c *Client) sendCloudhsmLicensesDestroy(ctx context.Context, params CloudhsmLicensesDestroyParams) (res *CloudhsmLicensesDestroyNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/cloudhsm/licenses/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmLicensesDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmLicensesDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmLicensesList invokes cloudhsm_licenses_list operation.
//
// GET /cloudhsm/licenses
func (c *Client) CloudhsmLicensesList(ctx context.Context) (*PaginatedCloudHSMSoftwareLicenseList, error) {
	res, err := c.sendCloudhsmLicensesList(ctx)
	return res, err
}

func (c *Client) sendCloudhsmLicensesList(ctx context.Context) (res *PaginatedCloudHSMSoftwareLicenseList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/cloudhsm/licenses"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmLicensesListOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmLicensesListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmLicensesRetrieve invokes cloudhsm_licenses_retrieve operation.
//
// GET /cloudhsm/licenses/{resource_id}
func (c *Client) CloudhsmLicensesRetrieve(ctx context.Context, params CloudhsmLicensesRetrieveParams) (*WrappedCloudHSMSoftwareLicense, error) {
	res, err := c.sendCloudhsmLicensesRetrieve(ctx, params)
	return res, err
}

func (c *Client) sendCloudhsmLicensesRetrieve(ctx context.Context, params CloudhsmLicensesRetrieveParams) (res *WrappedCloudHSMSoftwareLicense, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/cloudhsm/licenses/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmLicensesRetrieveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmLicensesRetrieveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CloudhsmLicensesUpdate invokes cloudhsm_licenses_update operation.
//
// PUT /cloudhsm/licenses/{resource_id}
func (c *Client) CloudhsmLicensesUpdate(ctx context.Context, request *WrappedCloudHSMSoftwareLicense, params CloudhsmLicensesUpdateParams) (*WrappedCloudHSMSoftwareLicense, error) {
	res, err := c.sendCloudhsmLicensesUpdate(ctx, request, params)
	return res, err
}

func (c *Client) sendCloudhsmLicensesUpdate(ctx context.Context, request *WrappedCloudHSMSoftwareLicense, params CloudhsmLicensesUpdateParams) (res *WrappedCloudHSMSoftwareLicense, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/cloudhsm/licenses/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCloudhsmLicensesUpdateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, CloudhsmLicensesUpdateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCloudhsmLicensesUpdateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysCreate invokes kms_keys_create operation.
//
// POST /kms/keys
func (c *Client) KmsKeysCreate(ctx context.Context, request *WrappedCreateKey) (*WrappedCreateKey, error) {
	res, err := c.sendKmsKeysCreate(ctx, request)
	return res, err
}

func (c *Client) sendKmsKeysCreate(ctx context.Context, request *WrappedCreateKey) (res *WrappedCreateKey, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/kms/keys"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeKmsKeysCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysDecrypt invokes kms_keys_decrypt operation.
//
// POST /kms/keys/{resource_id}/decrypt
func (c *Client) KmsKeysDecrypt(ctx context.Context, request *WrappedKeyCipher, params KmsKeysDecryptParams) (*WrappedKeyPlain, error) {
	res, err := c.sendKmsKeysDecrypt(ctx, request, params)
	return res, err
}

func (c *Client) sendKmsKeysDecrypt(ctx context.Context, request *WrappedKeyCipher, params KmsKeysDecryptParams) (res *WrappedKeyPlain, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/kms/keys/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/decrypt"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeKmsKeysDecryptRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysDecryptOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysDecryptResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysDestroy invokes kms_keys_destroy operation.
//
// DELETE /kms/keys/{resource_id}
func (c *Client) KmsKeysDestroy(ctx context.Context, params KmsKeysDestroyParams) error {
	_, err := c.sendKmsKeysDestroy(ctx, params)
	return err
}

func (c *Client) sendKmsKeysDestroy(ctx context.Context, params KmsKeysDestroyParams) (res *KmsKeysDestroyNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/kms/keys/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysEncrypt invokes kms_keys_encrypt operation.
//
// POST /kms/keys/{resource_id}/encrypt
func (c *Client) KmsKeysEncrypt(ctx context.Context, request *WrappedKeyPlain, params KmsKeysEncryptParams) (*WrappedKeyCipher, error) {
	res, err := c.sendKmsKeysEncrypt(ctx, request, params)
	return res, err
}

func (c *Client) sendKmsKeysEncrypt(ctx context.Context, request *WrappedKeyPlain, params KmsKeysEncryptParams) (res *WrappedKeyCipher, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/kms/keys/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/encrypt"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeKmsKeysEncryptRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysEncryptOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysEncryptResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysList invokes kms_keys_list operation.
//
// GET /kms/keys
func (c *Client) KmsKeysList(ctx context.Context) (*PaginatedKeyList, error) {
	res, err := c.sendKmsKeysList(ctx)
	return res, err
}

func (c *Client) sendKmsKeysList(ctx context.Context) (res *PaginatedKeyList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/kms/keys"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysListOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysRetrieve invokes kms_keys_retrieve operation.
//
// GET /kms/keys/{resource_id}
func (c *Client) KmsKeysRetrieve(ctx context.Context, params KmsKeysRetrieveParams) (*WrappedKey, error) {
	res, err := c.sendKmsKeysRetrieve(ctx, params)
	return res, err
}

func (c *Client) sendKmsKeysRetrieve(ctx context.Context, params KmsKeysRetrieveParams) (res *WrappedKey, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/kms/keys/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysRetrieveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysRetrieveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysRotate invokes kms_keys_rotate operation.
//
// POST /kms/keys/{resource_id}/rotate
func (c *Client) KmsKeysRotate(ctx context.Context, params KmsKeysRotateParams) (KmsKeysRotateRes, error) {
	res, err := c.sendKmsKeysRotate(ctx, params)
	return res, err
}

func (c *Client) sendKmsKeysRotate(ctx context.Context, params KmsKeysRotateParams) (res KmsKeysRotateRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/kms/keys/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/rotate"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysRotateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysRotateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysScheduleDestruction invokes kms_keys_schedule_destruction operation.
//
// POST /kms/keys/{resource_id}/schedule-destruction
func (c *Client) KmsKeysScheduleDestruction(ctx context.Context, request *WrappedScheduleDestructionKey, params KmsKeysScheduleDestructionParams) error {
	_, err := c.sendKmsKeysScheduleDestruction(ctx, request, params)
	return err
}

func (c *Client) sendKmsKeysScheduleDestruction(ctx context.Context, request *WrappedScheduleDestructionKey, params KmsKeysScheduleDestructionParams) (res *KmsKeysScheduleDestructionOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/kms/keys/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/schedule-destruction"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeKmsKeysScheduleDestructionRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysScheduleDestructionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysScheduleDestructionResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysStatus invokes kms_keys_status operation.
//
// POST /kms/keys/{resource_id}/status
func (c *Client) KmsKeysStatus(ctx context.Context, request *WrappedChangeKeyStatus, params KmsKeysStatusParams) error {
	_, err := c.sendKmsKeysStatus(ctx, request, params)
	return err
}

func (c *Client) sendKmsKeysStatus(ctx context.Context, request *WrappedChangeKeyStatus, params KmsKeysStatusParams) (res *KmsKeysStatusOK, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/kms/keys/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/status"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeKmsKeysStatusRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysStatusOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// KmsKeysUpdate invokes kms_keys_update operation.
//
// PUT /kms/keys/{resource_id}
func (c *Client) KmsKeysUpdate(ctx context.Context, request *WrappedKey, params KmsKeysUpdateParams) (*WrappedKey, error) {
	res, err := c.sendKmsKeysUpdate(ctx, request, params)
	return res, err
}

func (c *Client) sendKmsKeysUpdate(ctx context.Context, request *WrappedKey, params KmsKeysUpdateParams) (res *WrappedKey, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/kms/keys/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeKmsKeysUpdateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, KmsKeysUpdateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeKmsKeysUpdateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsCreate invokes secretmanager_vaults_create operation.
//
// POST /secretmanager/vaults
func (c *Client) SecretmanagerVaultsCreate(ctx context.Context, request *WrappedCreateVault) (*WrappedCreateVault, error) {
	res, err := c.sendSecretmanagerVaultsCreate(ctx, request)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsCreate(ctx context.Context, request *WrappedCreateVault) (res *WrappedCreateVault, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/secretmanager/vaults"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsDestroy invokes secretmanager_vaults_destroy operation.
//
// DELETE /secretmanager/vaults/{resource_id}
func (c *Client) SecretmanagerVaultsDestroy(ctx context.Context, params SecretmanagerVaultsDestroyParams) error {
	_, err := c.sendSecretmanagerVaultsDestroy(ctx, params)
	return err
}

func (c *Client) sendSecretmanagerVaultsDestroy(ctx context.Context, params SecretmanagerVaultsDestroyParams) (res *SecretmanagerVaultsDestroyNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsList invokes secretmanager_vaults_list operation.
//
// GET /secretmanager/vaults
func (c *Client) SecretmanagerVaultsList(ctx context.Context) (*PaginatedVaultList, error) {
	res, err := c.sendSecretmanagerVaultsList(ctx)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsList(ctx context.Context) (res *PaginatedVaultList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/secretmanager/vaults"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsListOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsRetrieve invokes secretmanager_vaults_retrieve operation.
//
// GET /secretmanager/vaults/{resource_id}
func (c *Client) SecretmanagerVaultsRetrieve(ctx context.Context, params SecretmanagerVaultsRetrieveParams) (*WrappedVault, error) {
	res, err := c.sendSecretmanagerVaultsRetrieve(ctx, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsRetrieve(ctx context.Context, params SecretmanagerVaultsRetrieveParams) (res *WrappedVault, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsRetrieveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsRetrieveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsSecretsCreate invokes secretmanager_vaults_secrets_create operation.
//
// POST /secretmanager/vaults/{vault_resource_id}/secrets
func (c *Client) SecretmanagerVaultsSecretsCreate(ctx context.Context, request *WrappedCreateSecret, params SecretmanagerVaultsSecretsCreateParams) (*WrappedCreateSecret, error) {
	res, err := c.sendSecretmanagerVaultsSecretsCreate(ctx, request, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsSecretsCreate(ctx context.Context, request *WrappedCreateSecret, params SecretmanagerVaultsSecretsCreateParams) (res *WrappedCreateSecret, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "vault_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "vault_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.VaultResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/secrets"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsSecretsCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsSecretsCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsSecretsCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsSecretsDestroy invokes secretmanager_vaults_secrets_destroy operation.
//
// DELETE /secretmanager/vaults/{vault_resource_id}/secrets
func (c *Client) SecretmanagerVaultsSecretsDestroy(ctx context.Context, request *WrappedDeleteSecret, params SecretmanagerVaultsSecretsDestroyParams) error {
	_, err := c.sendSecretmanagerVaultsSecretsDestroy(ctx, request, params)
	return err
}

func (c *Client) sendSecretmanagerVaultsSecretsDestroy(ctx context.Context, request *WrappedDeleteSecret, params SecretmanagerVaultsSecretsDestroyParams) (res *SecretmanagerVaultsSecretsDestroyNoContent, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "vault_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "vault_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.VaultResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/secrets"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsSecretsDestroyRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsSecretsDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsSecretsDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsSecretsList invokes secretmanager_vaults_secrets_list operation.
//
// GET /secretmanager/vaults/{vault_resource_id}/secrets
func (c *Client) SecretmanagerVaultsSecretsList(ctx context.Context, params SecretmanagerVaultsSecretsListParams) (*PaginatedSecretList, error) {
	res, err := c.sendSecretmanagerVaultsSecretsList(ctx, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsSecretsList(ctx context.Context, params SecretmanagerVaultsSecretsListParams) (res *PaginatedSecretList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "vault_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "vault_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.VaultResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/secrets"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsSecretsListOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsSecretsListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsSecretsUnveil invokes secretmanager_vaults_secrets_unveil operation.
//
// POST /secretmanager/vaults/{vault_resource_id}/secrets/unveil
func (c *Client) SecretmanagerVaultsSecretsUnveil(ctx context.Context, request *WrappedUnvail, params SecretmanagerVaultsSecretsUnveilParams) (*WrappedUnvail, error) {
	res, err := c.sendSecretmanagerVaultsSecretsUnveil(ctx, request, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsSecretsUnveil(ctx context.Context, request *WrappedUnvail, params SecretmanagerVaultsSecretsUnveilParams) (res *WrappedUnvail, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "vault_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "vault_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.VaultResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/secrets/unveil"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsSecretsUnveilRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsSecretsUnveilOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsSecretsUnveilResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsUpdate invokes secretmanager_vaults_update operation.
//
// PUT /secretmanager/vaults/{resource_id}
func (c *Client) SecretmanagerVaultsUpdate(ctx context.Context, request *WrappedVault, params SecretmanagerVaultsUpdateParams) (*WrappedVault, error) {
	res, err := c.sendSecretmanagerVaultsUpdate(ctx, request, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsUpdate(ctx context.Context, request *WrappedVault, params SecretmanagerVaultsUpdateParams) (res *WrappedVault, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsUpdateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsUpdateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsUpdateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
