// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"github.com/go-faster/errors"
)

// * `precreate` - 準備中
// * `available` - 利用可能
// * `discontinued` - 廃止.
// Ref: #/components/schemas/AvailabilityEnum
type AvailabilityEnum string

const (
	AvailabilityEnumPrecreate    AvailabilityEnum = "precreate"
	AvailabilityEnumAvailable    AvailabilityEnum = "available"
	AvailabilityEnumDiscontinued AvailabilityEnum = "discontinued"
)

// AllValues returns all AvailabilityEnum values.
func (AvailabilityEnum) AllValues() []AvailabilityEnum {
	return []AvailabilityEnum{
		AvailabilityEnumPrecreate,
		AvailabilityEnumAvailable,
		AvailabilityEnumDiscontinued,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AvailabilityEnum) MarshalText() ([]byte, error) {
	switch s {
	case AvailabilityEnumPrecreate:
		return []byte(s), nil
	case AvailabilityEnumAvailable:
		return []byte(s), nil
	case AvailabilityEnumDiscontinued:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AvailabilityEnum) UnmarshalText(data []byte) error {
	switch AvailabilityEnum(data) {
	case AvailabilityEnumPrecreate:
		*s = AvailabilityEnumPrecreate
		return nil
	case AvailabilityEnumAvailable:
		*s = AvailabilityEnumAvailable
		return nil
	case AvailabilityEnumDiscontinued:
		*s = AvailabilityEnumDiscontinued
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BasicAuth struct {
	Username string
	Password string
	Roles    []string
}

// GetUsername returns the value of Username.
func (s *BasicAuth) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *BasicAuth) GetPassword() string {
	return s.Password
}

// GetRoles returns the value of Roles.
func (s *BasicAuth) GetRoles() []string {
	return s.Roles
}

// SetUsername sets the value of Username.
func (s *BasicAuth) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *BasicAuth) SetPassword(val string) {
	s.Password = val
}

// SetRoles sets the value of Roles.
func (s *BasicAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ChangeKeyStatus
type ChangeKeyStatus struct {
	Status OptChangeKeyStatusStatus `json:"Status"`
}

// GetStatus returns the value of Status.
func (s *ChangeKeyStatus) GetStatus() OptChangeKeyStatusStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *ChangeKeyStatus) SetStatus(val OptChangeKeyStatusStatus) {
	s.Status = val
}

type ChangeKeyStatusStatus string

const (
	ChangeKeyStatusStatusActive     ChangeKeyStatusStatus = "active"
	ChangeKeyStatusStatusRestricted ChangeKeyStatusStatus = "restricted"
	ChangeKeyStatusStatusSuspended  ChangeKeyStatusStatus = "suspended"
)

// AllValues returns all ChangeKeyStatusStatus values.
func (ChangeKeyStatusStatus) AllValues() []ChangeKeyStatusStatus {
	return []ChangeKeyStatusStatus{
		ChangeKeyStatusStatusActive,
		ChangeKeyStatusStatusRestricted,
		ChangeKeyStatusStatusSuspended,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChangeKeyStatusStatus) MarshalText() ([]byte, error) {
	switch s {
	case ChangeKeyStatusStatusActive:
		return []byte(s), nil
	case ChangeKeyStatusStatusRestricted:
		return []byte(s), nil
	case ChangeKeyStatusStatusSuspended:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChangeKeyStatusStatus) UnmarshalText(data []byte) error {
	switch ChangeKeyStatusStatus(data) {
	case ChangeKeyStatusStatusActive:
		*s = ChangeKeyStatusStatusActive
		return nil
	case ChangeKeyStatusStatusRestricted:
		*s = ChangeKeyStatusStatusRestricted
		return nil
	case ChangeKeyStatusStatusSuspended:
		*s = ChangeKeyStatusStatusSuspended
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CloudHSM
type CloudHSM struct {
	ID                 string                 `json:"ID"`
	CreatedAt          DateTime               `json:"CreatedAt"`
	ModifiedAt         DateTime               `json:"ModifiedAt"`
	ServiceClass       ServiceClassEnum       `json:"ServiceClass"`
	Availability       AvailabilityEnum       `json:"Availability"`
	Name               string                 `json:"Name"`
	Description        OptString              `json:"Description"`
	Tags               []string               `json:"Tags"`
	IPv4NetworkAddress string                 `json:"IPv4NetworkAddress"`
	IPv4PrefixLength   int                    `json:"IPv4PrefixLength"`
	IPv4Address        string                 `json:"IPv4Address"`
	LocalRouter        NilCloudHSMLocalRouter `json:"LocalRouter"`
}

// GetID returns the value of ID.
func (s *CloudHSM) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CloudHSM) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CloudHSM) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *CloudHSM) GetServiceClass() ServiceClassEnum {
	return s.ServiceClass
}

// GetAvailability returns the value of Availability.
func (s *CloudHSM) GetAvailability() AvailabilityEnum {
	return s.Availability
}

// GetName returns the value of Name.
func (s *CloudHSM) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CloudHSM) GetDescription() OptString {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *CloudHSM) GetTags() []string {
	return s.Tags
}

// GetIPv4NetworkAddress returns the value of IPv4NetworkAddress.
func (s *CloudHSM) GetIPv4NetworkAddress() string {
	return s.IPv4NetworkAddress
}

// GetIPv4PrefixLength returns the value of IPv4PrefixLength.
func (s *CloudHSM) GetIPv4PrefixLength() int {
	return s.IPv4PrefixLength
}

// GetIPv4Address returns the value of IPv4Address.
func (s *CloudHSM) GetIPv4Address() string {
	return s.IPv4Address
}

// GetLocalRouter returns the value of LocalRouter.
func (s *CloudHSM) GetLocalRouter() NilCloudHSMLocalRouter {
	return s.LocalRouter
}

// SetID sets the value of ID.
func (s *CloudHSM) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CloudHSM) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CloudHSM) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CloudHSM) SetServiceClass(val ServiceClassEnum) {
	s.ServiceClass = val
}

// SetAvailability sets the value of Availability.
func (s *CloudHSM) SetAvailability(val AvailabilityEnum) {
	s.Availability = val
}

// SetName sets the value of Name.
func (s *CloudHSM) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CloudHSM) SetDescription(val OptString) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *CloudHSM) SetTags(val []string) {
	s.Tags = val
}

// SetIPv4NetworkAddress sets the value of IPv4NetworkAddress.
func (s *CloudHSM) SetIPv4NetworkAddress(val string) {
	s.IPv4NetworkAddress = val
}

// SetIPv4PrefixLength sets the value of IPv4PrefixLength.
func (s *CloudHSM) SetIPv4PrefixLength(val int) {
	s.IPv4PrefixLength = val
}

// SetIPv4Address sets the value of IPv4Address.
func (s *CloudHSM) SetIPv4Address(val string) {
	s.IPv4Address = val
}

// SetLocalRouter sets the value of LocalRouter.
func (s *CloudHSM) SetLocalRouter(val NilCloudHSMLocalRouter) {
	s.LocalRouter = val
}

// Ref: #/components/schemas/CloudHSMClient
type CloudHSMClient struct {
	ID           string           `json:"ID"`
	CreatedAt    DateTime         `json:"CreatedAt"`
	ModifiedAt   DateTime         `json:"ModifiedAt"`
	Availability AvailabilityEnum `json:"Availability"`
	Name         string           `json:"Name"`
	Certificate  string           `json:"Certificate"`
}

// GetID returns the value of ID.
func (s *CloudHSMClient) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CloudHSMClient) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CloudHSMClient) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetAvailability returns the value of Availability.
func (s *CloudHSMClient) GetAvailability() AvailabilityEnum {
	return s.Availability
}

// GetName returns the value of Name.
func (s *CloudHSMClient) GetName() string {
	return s.Name
}

// GetCertificate returns the value of Certificate.
func (s *CloudHSMClient) GetCertificate() string {
	return s.Certificate
}

// SetID sets the value of ID.
func (s *CloudHSMClient) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CloudHSMClient) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CloudHSMClient) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetAvailability sets the value of Availability.
func (s *CloudHSMClient) SetAvailability(val AvailabilityEnum) {
	s.Availability = val
}

// SetName sets the value of Name.
func (s *CloudHSMClient) SetName(val string) {
	s.Name = val
}

// SetCertificate sets the value of Certificate.
func (s *CloudHSMClient) SetCertificate(val string) {
	s.Certificate = val
}

// Ref: #/components/schemas/CloudHSMLocalRouter
type CloudHSMLocalRouter struct {
	ResourceID OptString `json:"ResourceID"`
	SecretKey  OptString `json:"SecretKey"`
}

// GetResourceID returns the value of ResourceID.
func (s *CloudHSMLocalRouter) GetResourceID() OptString {
	return s.ResourceID
}

// GetSecretKey returns the value of SecretKey.
func (s *CloudHSMLocalRouter) GetSecretKey() OptString {
	return s.SecretKey
}

// SetResourceID sets the value of ResourceID.
func (s *CloudHSMLocalRouter) SetResourceID(val OptString) {
	s.ResourceID = val
}

// SetSecretKey sets the value of SecretKey.
func (s *CloudHSMLocalRouter) SetSecretKey(val OptString) {
	s.SecretKey = val
}

// Ref: #/components/schemas/CloudHSMPeer
type CloudHSMPeer struct {
	ID        string `json:"ID"`
	SecretKey string `json:"SecretKey"`
}

// GetID returns the value of ID.
func (s *CloudHSMPeer) GetID() string {
	return s.ID
}

// GetSecretKey returns the value of SecretKey.
func (s *CloudHSMPeer) GetSecretKey() string {
	return s.SecretKey
}

// SetID sets the value of ID.
func (s *CloudHSMPeer) SetID(val string) {
	s.ID = val
}

// SetSecretKey sets the value of SecretKey.
func (s *CloudHSMPeer) SetSecretKey(val string) {
	s.SecretKey = val
}

// Ref: #/components/schemas/CloudHSMPeerList
type CloudHSMPeerList struct {
	Peers []CloudHSMPeer `json:"Peers"`
}

// GetPeers returns the value of Peers.
func (s *CloudHSMPeerList) GetPeers() []CloudHSMPeer {
	return s.Peers
}

// SetPeers sets the value of Peers.
func (s *CloudHSMPeerList) SetPeers(val []CloudHSMPeer) {
	s.Peers = val
}

// Ref: #/components/schemas/CloudHSMSoftwareLicense
type CloudHSMSoftwareLicense struct {
	ID           string                                  `json:"ID"`
	CreatedAt    DateTime                                `json:"CreatedAt"`
	ModifiedAt   DateTime                                `json:"ModifiedAt"`
	ServiceClass CloudHSMSoftwareLicenseServiceClassEnum `json:"ServiceClass"`
	Name         string                                  `json:"Name"`
	Description  string                                  `json:"Description"`
	Tags         []string                                `json:"Tags"`
}

// GetID returns the value of ID.
func (s *CloudHSMSoftwareLicense) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CloudHSMSoftwareLicense) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CloudHSMSoftwareLicense) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *CloudHSMSoftwareLicense) GetServiceClass() CloudHSMSoftwareLicenseServiceClassEnum {
	return s.ServiceClass
}

// GetName returns the value of Name.
func (s *CloudHSMSoftwareLicense) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CloudHSMSoftwareLicense) GetDescription() string {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *CloudHSMSoftwareLicense) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *CloudHSMSoftwareLicense) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CloudHSMSoftwareLicense) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CloudHSMSoftwareLicense) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CloudHSMSoftwareLicense) SetServiceClass(val CloudHSMSoftwareLicenseServiceClassEnum) {
	s.ServiceClass = val
}

// SetName sets the value of Name.
func (s *CloudHSMSoftwareLicense) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CloudHSMSoftwareLicense) SetDescription(val string) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *CloudHSMSoftwareLicense) SetTags(val []string) {
	s.Tags = val
}

// * `cloud/cloudhsm/license/l7` - for Type-L7 Client.
// Ref: #/components/schemas/CloudHSMSoftwareLicenseServiceClassEnum
type CloudHSMSoftwareLicenseServiceClassEnum string

const (
	CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7 CloudHSMSoftwareLicenseServiceClassEnum = "cloud/cloudhsm/license/l7"
)

// AllValues returns all CloudHSMSoftwareLicenseServiceClassEnum values.
func (CloudHSMSoftwareLicenseServiceClassEnum) AllValues() []CloudHSMSoftwareLicenseServiceClassEnum {
	return []CloudHSMSoftwareLicenseServiceClassEnum{
		CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CloudHSMSoftwareLicenseServiceClassEnum) MarshalText() ([]byte, error) {
	switch s {
	case CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CloudHSMSoftwareLicenseServiceClassEnum) UnmarshalText(data []byte) error {
	switch CloudHSMSoftwareLicenseServiceClassEnum(data) {
	case CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7:
		*s = CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// CloudhsmCloudhsmsClientsDestroyNoContent is response for CloudhsmCloudhsmsClientsDestroy operation.
type CloudhsmCloudhsmsClientsDestroyNoContent struct{}

// CloudhsmCloudhsmsDestroyNoContent is response for CloudhsmCloudhsmsDestroy operation.
type CloudhsmCloudhsmsDestroyNoContent struct{}

// CloudhsmCloudhsmsPeersDestroyNoContent is response for CloudhsmCloudhsmsPeersDestroy operation.
type CloudhsmCloudhsmsPeersDestroyNoContent struct{}

// CloudhsmLicensesDestroyNoContent is response for CloudhsmLicensesDestroy operation.
type CloudhsmLicensesDestroyNoContent struct{}

// Ref: #/components/schemas/CreateCloudHSM
type CreateCloudHSM struct {
	ID                 string           `json:"ID"`
	CreatedAt          DateTime         `json:"CreatedAt"`
	ModifiedAt         DateTime         `json:"ModifiedAt"`
	ServiceClass       ServiceClassEnum `json:"ServiceClass"`
	Availability       AvailabilityEnum `json:"Availability"`
	Name               string           `json:"Name"`
	Description        OptString        `json:"Description"`
	Tags               []string         `json:"Tags"`
	IPv4NetworkAddress string           `json:"IPv4NetworkAddress"`
	IPv4PrefixLength   int              `json:"IPv4PrefixLength"`
	IPv4Address        string           `json:"IPv4Address"`
}

// GetID returns the value of ID.
func (s *CreateCloudHSM) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateCloudHSM) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CreateCloudHSM) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *CreateCloudHSM) GetServiceClass() ServiceClassEnum {
	return s.ServiceClass
}

// GetAvailability returns the value of Availability.
func (s *CreateCloudHSM) GetAvailability() AvailabilityEnum {
	return s.Availability
}

// GetName returns the value of Name.
func (s *CreateCloudHSM) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateCloudHSM) GetDescription() OptString {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *CreateCloudHSM) GetTags() []string {
	return s.Tags
}

// GetIPv4NetworkAddress returns the value of IPv4NetworkAddress.
func (s *CreateCloudHSM) GetIPv4NetworkAddress() string {
	return s.IPv4NetworkAddress
}

// GetIPv4PrefixLength returns the value of IPv4PrefixLength.
func (s *CreateCloudHSM) GetIPv4PrefixLength() int {
	return s.IPv4PrefixLength
}

// GetIPv4Address returns the value of IPv4Address.
func (s *CreateCloudHSM) GetIPv4Address() string {
	return s.IPv4Address
}

// SetID sets the value of ID.
func (s *CreateCloudHSM) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateCloudHSM) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CreateCloudHSM) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CreateCloudHSM) SetServiceClass(val ServiceClassEnum) {
	s.ServiceClass = val
}

// SetAvailability sets the value of Availability.
func (s *CreateCloudHSM) SetAvailability(val AvailabilityEnum) {
	s.Availability = val
}

// SetName sets the value of Name.
func (s *CreateCloudHSM) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateCloudHSM) SetDescription(val OptString) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *CreateCloudHSM) SetTags(val []string) {
	s.Tags = val
}

// SetIPv4NetworkAddress sets the value of IPv4NetworkAddress.
func (s *CreateCloudHSM) SetIPv4NetworkAddress(val string) {
	s.IPv4NetworkAddress = val
}

// SetIPv4PrefixLength sets the value of IPv4PrefixLength.
func (s *CreateCloudHSM) SetIPv4PrefixLength(val int) {
	s.IPv4PrefixLength = val
}

// SetIPv4Address sets the value of IPv4Address.
func (s *CreateCloudHSM) SetIPv4Address(val string) {
	s.IPv4Address = val
}

// Ref: #/components/schemas/CreateCloudHSMClient
type CreateCloudHSMClient struct {
	ID           string           `json:"ID"`
	CreatedAt    DateTime         `json:"CreatedAt"`
	ModifiedAt   DateTime         `json:"ModifiedAt"`
	Availability AvailabilityEnum `json:"Availability"`
	Name         string           `json:"Name"`
	Certificate  string           `json:"Certificate"`
}

// GetID returns the value of ID.
func (s *CreateCloudHSMClient) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateCloudHSMClient) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CreateCloudHSMClient) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetAvailability returns the value of Availability.
func (s *CreateCloudHSMClient) GetAvailability() AvailabilityEnum {
	return s.Availability
}

// GetName returns the value of Name.
func (s *CreateCloudHSMClient) GetName() string {
	return s.Name
}

// GetCertificate returns the value of Certificate.
func (s *CreateCloudHSMClient) GetCertificate() string {
	return s.Certificate
}

// SetID sets the value of ID.
func (s *CreateCloudHSMClient) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateCloudHSMClient) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CreateCloudHSMClient) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetAvailability sets the value of Availability.
func (s *CreateCloudHSMClient) SetAvailability(val AvailabilityEnum) {
	s.Availability = val
}

// SetName sets the value of Name.
func (s *CreateCloudHSMClient) SetName(val string) {
	s.Name = val
}

// SetCertificate sets the value of Certificate.
func (s *CreateCloudHSMClient) SetCertificate(val string) {
	s.Certificate = val
}

// Ref: #/components/schemas/CreateCloudHSMPeer
type CreateCloudHSMPeer struct {
	ID        string `json:"ID"`
	SecretKey string `json:"SecretKey"`
}

// GetID returns the value of ID.
func (s *CreateCloudHSMPeer) GetID() string {
	return s.ID
}

// GetSecretKey returns the value of SecretKey.
func (s *CreateCloudHSMPeer) GetSecretKey() string {
	return s.SecretKey
}

// SetID sets the value of ID.
func (s *CreateCloudHSMPeer) SetID(val string) {
	s.ID = val
}

// SetSecretKey sets the value of SecretKey.
func (s *CreateCloudHSMPeer) SetSecretKey(val string) {
	s.SecretKey = val
}

// Ref: #/components/schemas/CreateCloudHSMSoftwareLicense
type CreateCloudHSMSoftwareLicense struct {
	ID           string                                  `json:"ID"`
	CreatedAt    DateTime                                `json:"CreatedAt"`
	ModifiedAt   DateTime                                `json:"ModifiedAt"`
	ServiceClass CloudHSMSoftwareLicenseServiceClassEnum `json:"ServiceClass"`
	Name         string                                  `json:"Name"`
	Description  OptString                               `json:"Description"`
	Tags         []string                                `json:"Tags"`
}

// GetID returns the value of ID.
func (s *CreateCloudHSMSoftwareLicense) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateCloudHSMSoftwareLicense) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CreateCloudHSMSoftwareLicense) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *CreateCloudHSMSoftwareLicense) GetServiceClass() CloudHSMSoftwareLicenseServiceClassEnum {
	return s.ServiceClass
}

// GetName returns the value of Name.
func (s *CreateCloudHSMSoftwareLicense) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateCloudHSMSoftwareLicense) GetDescription() OptString {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *CreateCloudHSMSoftwareLicense) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *CreateCloudHSMSoftwareLicense) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateCloudHSMSoftwareLicense) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CreateCloudHSMSoftwareLicense) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CreateCloudHSMSoftwareLicense) SetServiceClass(val CloudHSMSoftwareLicenseServiceClassEnum) {
	s.ServiceClass = val
}

// SetName sets the value of Name.
func (s *CreateCloudHSMSoftwareLicense) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateCloudHSMSoftwareLicense) SetDescription(val OptString) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *CreateCloudHSMSoftwareLicense) SetTags(val []string) {
	s.Tags = val
}

// Ref: #/components/schemas/CreateKey
type CreateKey struct {
	ID          string        `json:"ID"`
	CreatedAt   DateTime      `json:"CreatedAt"`
	ModifiedAt  DateTime      `json:"ModifiedAt"`
	Name        string        `json:"Name"`
	Description OptString     `json:"Description"`
	KeyOrigin   KeyOriginEnum `json:"KeyOrigin"`
	Tags        []string      `json:"Tags"`
	PlainKey    OptString     `json:"PlainKey"`
}

// GetID returns the value of ID.
func (s *CreateKey) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateKey) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CreateKey) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetName returns the value of Name.
func (s *CreateKey) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateKey) GetDescription() OptString {
	return s.Description
}

// GetKeyOrigin returns the value of KeyOrigin.
func (s *CreateKey) GetKeyOrigin() KeyOriginEnum {
	return s.KeyOrigin
}

// GetTags returns the value of Tags.
func (s *CreateKey) GetTags() []string {
	return s.Tags
}

// GetPlainKey returns the value of PlainKey.
func (s *CreateKey) GetPlainKey() OptString {
	return s.PlainKey
}

// SetID sets the value of ID.
func (s *CreateKey) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateKey) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CreateKey) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetName sets the value of Name.
func (s *CreateKey) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateKey) SetDescription(val OptString) {
	s.Description = val
}

// SetKeyOrigin sets the value of KeyOrigin.
func (s *CreateKey) SetKeyOrigin(val KeyOriginEnum) {
	s.KeyOrigin = val
}

// SetTags sets the value of Tags.
func (s *CreateKey) SetTags(val []string) {
	s.Tags = val
}

// SetPlainKey sets the value of PlainKey.
func (s *CreateKey) SetPlainKey(val OptString) {
	s.PlainKey = val
}

// Ref: #/components/schemas/CreateSecret
type CreateSecret struct {
	Name          string `json:"Name"`
	Value         string `json:"Value"`
	LatestVersion int    `json:"LatestVersion"`
}

// GetName returns the value of Name.
func (s *CreateSecret) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *CreateSecret) GetValue() string {
	return s.Value
}

// GetLatestVersion returns the value of LatestVersion.
func (s *CreateSecret) GetLatestVersion() int {
	return s.LatestVersion
}

// SetName sets the value of Name.
func (s *CreateSecret) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *CreateSecret) SetValue(val string) {
	s.Value = val
}

// SetLatestVersion sets the value of LatestVersion.
func (s *CreateSecret) SetLatestVersion(val int) {
	s.LatestVersion = val
}

// Ref: #/components/schemas/CreateVault
type CreateVault struct {
	ID          string    `json:"ID"`
	CreatedAt   DateTime  `json:"CreatedAt"`
	ModifiedAt  DateTime  `json:"ModifiedAt"`
	Name        string    `json:"Name"`
	Description OptString `json:"Description"`
	KmsKeyID    string    `json:"KmsKeyID"`
	Tags        []string  `json:"Tags"`
}

// GetID returns the value of ID.
func (s *CreateVault) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateVault) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CreateVault) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetName returns the value of Name.
func (s *CreateVault) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateVault) GetDescription() OptString {
	return s.Description
}

// GetKmsKeyID returns the value of KmsKeyID.
func (s *CreateVault) GetKmsKeyID() string {
	return s.KmsKeyID
}

// GetTags returns the value of Tags.
func (s *CreateVault) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *CreateVault) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateVault) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CreateVault) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetName sets the value of Name.
func (s *CreateVault) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateVault) SetDescription(val OptString) {
	s.Description = val
}

// SetKmsKeyID sets the value of KmsKeyID.
func (s *CreateVault) SetKmsKeyID(val string) {
	s.KmsKeyID = val
}

// SetTags sets the value of Tags.
func (s *CreateVault) SetTags(val []string) {
	s.Tags = val
}

type DateTime string

// Ref: #/components/schemas/DeleteSecret
type DeleteSecret struct {
	Name string `json:"Name"`
}

// GetName returns the value of Name.
func (s *DeleteSecret) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *DeleteSecret) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/Key
type Key struct {
	ID            string                 `json:"ID"`
	CreatedAt     DateTime               `json:"CreatedAt"`
	ModifiedAt    DateTime               `json:"ModifiedAt"`
	ServiceClass  OptKeyServiceClassEnum `json:"ServiceClass"`
	Name          string                 `json:"Name"`
	Description   string                 `json:"Description"`
	KeyOrigin     KeyOriginEnum          `json:"KeyOrigin"`
	LatestVersion OptInt                 `json:"LatestVersion"`
	Status        KeyStatusEnum          `json:"Status"`
	Tags          []string               `json:"Tags"`
}

// GetID returns the value of ID.
func (s *Key) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Key) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *Key) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *Key) GetServiceClass() OptKeyServiceClassEnum {
	return s.ServiceClass
}

// GetName returns the value of Name.
func (s *Key) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Key) GetDescription() string {
	return s.Description
}

// GetKeyOrigin returns the value of KeyOrigin.
func (s *Key) GetKeyOrigin() KeyOriginEnum {
	return s.KeyOrigin
}

// GetLatestVersion returns the value of LatestVersion.
func (s *Key) GetLatestVersion() OptInt {
	return s.LatestVersion
}

// GetStatus returns the value of Status.
func (s *Key) GetStatus() KeyStatusEnum {
	return s.Status
}

// GetTags returns the value of Tags.
func (s *Key) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *Key) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Key) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *Key) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *Key) SetServiceClass(val OptKeyServiceClassEnum) {
	s.ServiceClass = val
}

// SetName sets the value of Name.
func (s *Key) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Key) SetDescription(val string) {
	s.Description = val
}

// SetKeyOrigin sets the value of KeyOrigin.
func (s *Key) SetKeyOrigin(val KeyOriginEnum) {
	s.KeyOrigin = val
}

// SetLatestVersion sets the value of LatestVersion.
func (s *Key) SetLatestVersion(val OptInt) {
	s.LatestVersion = val
}

// SetStatus sets the value of Status.
func (s *Key) SetStatus(val KeyStatusEnum) {
	s.Status = val
}

// SetTags sets the value of Tags.
func (s *Key) SetTags(val []string) {
	s.Tags = val
}

// Ref: #/components/schemas/KeyCipher
type KeyCipher struct {
	// 暗号化エンドポイントのレスポンス.
	Cipher string `json:"Cipher"`
}

// GetCipher returns the value of Cipher.
func (s *KeyCipher) GetCipher() string {
	return s.Cipher
}

// SetCipher sets the value of Cipher.
func (s *KeyCipher) SetCipher(val string) {
	s.Cipher = val
}

// * `aes-256-gcm` - AES256-GCMモードでの暗号化(default)
// * `aes-256-cbc` - AES256-CBCモードでの暗号化
// * `aes-256-kw` - AES256-KWモードでの暗号化.
// Ref: #/components/schemas/KeyEncryptAlgoEnum
type KeyEncryptAlgoEnum string

const (
	KeyEncryptAlgoEnumAes256Gcm KeyEncryptAlgoEnum = "aes-256-gcm"
	KeyEncryptAlgoEnumAes256Cbc KeyEncryptAlgoEnum = "aes-256-cbc"
	KeyEncryptAlgoEnumAes256Kw  KeyEncryptAlgoEnum = "aes-256-kw"
)

// AllValues returns all KeyEncryptAlgoEnum values.
func (KeyEncryptAlgoEnum) AllValues() []KeyEncryptAlgoEnum {
	return []KeyEncryptAlgoEnum{
		KeyEncryptAlgoEnumAes256Gcm,
		KeyEncryptAlgoEnumAes256Cbc,
		KeyEncryptAlgoEnumAes256Kw,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s KeyEncryptAlgoEnum) MarshalText() ([]byte, error) {
	switch s {
	case KeyEncryptAlgoEnumAes256Gcm:
		return []byte(s), nil
	case KeyEncryptAlgoEnumAes256Cbc:
		return []byte(s), nil
	case KeyEncryptAlgoEnumAes256Kw:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *KeyEncryptAlgoEnum) UnmarshalText(data []byte) error {
	switch KeyEncryptAlgoEnum(data) {
	case KeyEncryptAlgoEnumAes256Gcm:
		*s = KeyEncryptAlgoEnumAes256Gcm
		return nil
	case KeyEncryptAlgoEnumAes256Cbc:
		*s = KeyEncryptAlgoEnumAes256Cbc
		return nil
	case KeyEncryptAlgoEnumAes256Kw:
		*s = KeyEncryptAlgoEnumAes256Kw
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// * `generated` - 生成
// * `imported` - インポート.
// Ref: #/components/schemas/KeyOriginEnum
type KeyOriginEnum string

const (
	KeyOriginEnumGenerated KeyOriginEnum = "generated"
	KeyOriginEnumImported  KeyOriginEnum = "imported"
)

// AllValues returns all KeyOriginEnum values.
func (KeyOriginEnum) AllValues() []KeyOriginEnum {
	return []KeyOriginEnum{
		KeyOriginEnumGenerated,
		KeyOriginEnumImported,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s KeyOriginEnum) MarshalText() ([]byte, error) {
	switch s {
	case KeyOriginEnumGenerated:
		return []byte(s), nil
	case KeyOriginEnumImported:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *KeyOriginEnum) UnmarshalText(data []byte) error {
	switch KeyOriginEnum(data) {
	case KeyOriginEnumGenerated:
		*s = KeyOriginEnumGenerated
		return nil
	case KeyOriginEnumImported:
		*s = KeyOriginEnumImported
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/KeyPlain
type KeyPlain struct {
	// Base64でエンコードされた平文.
	Plain string                `json:"Plain"`
	Algo  OptKeyEncryptAlgoEnum `json:"Algo"`
}

// GetPlain returns the value of Plain.
func (s *KeyPlain) GetPlain() string {
	return s.Plain
}

// GetAlgo returns the value of Algo.
func (s *KeyPlain) GetAlgo() OptKeyEncryptAlgoEnum {
	return s.Algo
}

// SetPlain sets the value of Plain.
func (s *KeyPlain) SetPlain(val string) {
	s.Plain = val
}

// SetAlgo sets the value of Algo.
func (s *KeyPlain) SetAlgo(val OptKeyEncryptAlgoEnum) {
	s.Algo = val
}

// Ref: #/components/schemas/KeyServiceClassEnum
type KeyServiceClassEnum string

const (
	KeyServiceClassEnumCloudKmsKey       KeyServiceClassEnum = "cloud/kms/key"
	KeyServiceClassEnumCloudKmsKeyLegacy KeyServiceClassEnum = "cloud/kms/key/legacy"
)

// AllValues returns all KeyServiceClassEnum values.
func (KeyServiceClassEnum) AllValues() []KeyServiceClassEnum {
	return []KeyServiceClassEnum{
		KeyServiceClassEnumCloudKmsKey,
		KeyServiceClassEnumCloudKmsKeyLegacy,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s KeyServiceClassEnum) MarshalText() ([]byte, error) {
	switch s {
	case KeyServiceClassEnumCloudKmsKey:
		return []byte(s), nil
	case KeyServiceClassEnumCloudKmsKeyLegacy:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *KeyServiceClassEnum) UnmarshalText(data []byte) error {
	switch KeyServiceClassEnum(data) {
	case KeyServiceClassEnumCloudKmsKey:
		*s = KeyServiceClassEnumCloudKmsKey
		return nil
	case KeyServiceClassEnumCloudKmsKeyLegacy:
		*s = KeyServiceClassEnumCloudKmsKeyLegacy
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// * `active` - 有効
// * `restricted` - 復号と署名検証にのみ利用可能
// * `suspended` - 利用不可
// * `pending_destruction` - 削除猶予.
// Ref: #/components/schemas/KeyStatusEnum
type KeyStatusEnum string

const (
	KeyStatusEnumActive             KeyStatusEnum = "active"
	KeyStatusEnumRestricted         KeyStatusEnum = "restricted"
	KeyStatusEnumSuspended          KeyStatusEnum = "suspended"
	KeyStatusEnumPendingDestruction KeyStatusEnum = "pending_destruction"
)

// AllValues returns all KeyStatusEnum values.
func (KeyStatusEnum) AllValues() []KeyStatusEnum {
	return []KeyStatusEnum{
		KeyStatusEnumActive,
		KeyStatusEnumRestricted,
		KeyStatusEnumSuspended,
		KeyStatusEnumPendingDestruction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s KeyStatusEnum) MarshalText() ([]byte, error) {
	switch s {
	case KeyStatusEnumActive:
		return []byte(s), nil
	case KeyStatusEnumRestricted:
		return []byte(s), nil
	case KeyStatusEnumSuspended:
		return []byte(s), nil
	case KeyStatusEnumPendingDestruction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *KeyStatusEnum) UnmarshalText(data []byte) error {
	switch KeyStatusEnum(data) {
	case KeyStatusEnumActive:
		*s = KeyStatusEnumActive
		return nil
	case KeyStatusEnumRestricted:
		*s = KeyStatusEnumRestricted
		return nil
	case KeyStatusEnumSuspended:
		*s = KeyStatusEnumSuspended
		return nil
	case KeyStatusEnumPendingDestruction:
		*s = KeyStatusEnumPendingDestruction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// KmsKeysDestroyNoContent is response for KmsKeysDestroy operation.
type KmsKeysDestroyNoContent struct{}

// KmsKeysRotateForbidden is response for KmsKeysRotate operation.
type KmsKeysRotateForbidden struct{}

func (*KmsKeysRotateForbidden) kmsKeysRotateRes() {}

// KmsKeysScheduleDestructionOK is response for KmsKeysScheduleDestruction operation.
type KmsKeysScheduleDestructionOK struct{}

// KmsKeysStatusOK is response for KmsKeysStatus operation.
type KmsKeysStatusOK struct{}

// NewNilCloudHSMLocalRouter returns new NilCloudHSMLocalRouter with value set to v.
func NewNilCloudHSMLocalRouter(v CloudHSMLocalRouter) NilCloudHSMLocalRouter {
	return NilCloudHSMLocalRouter{
		Value: v,
	}
}

// NilCloudHSMLocalRouter is nullable CloudHSMLocalRouter.
type NilCloudHSMLocalRouter struct {
	Value CloudHSMLocalRouter
	Null  bool
}

// SetTo sets value to v.
func (o *NilCloudHSMLocalRouter) SetTo(v CloudHSMLocalRouter) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilCloudHSMLocalRouter) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilCloudHSMLocalRouter) SetToNull() {
	o.Null = true
	var v CloudHSMLocalRouter
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilCloudHSMLocalRouter) Get() (v CloudHSMLocalRouter, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilCloudHSMLocalRouter) Or(d CloudHSMLocalRouter) CloudHSMLocalRouter {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptChangeKeyStatusStatus returns new OptChangeKeyStatusStatus with value set to v.
func NewOptChangeKeyStatusStatus(v ChangeKeyStatusStatus) OptChangeKeyStatusStatus {
	return OptChangeKeyStatusStatus{
		Value: v,
		Set:   true,
	}
}

// OptChangeKeyStatusStatus is optional ChangeKeyStatusStatus.
type OptChangeKeyStatusStatus struct {
	Value ChangeKeyStatusStatus
	Set   bool
}

// IsSet returns true if OptChangeKeyStatusStatus was set.
func (o OptChangeKeyStatusStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChangeKeyStatusStatus) Reset() {
	var v ChangeKeyStatusStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChangeKeyStatusStatus) SetTo(v ChangeKeyStatusStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChangeKeyStatusStatus) Get() (v ChangeKeyStatusStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChangeKeyStatusStatus) Or(d ChangeKeyStatusStatus) ChangeKeyStatusStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptKeyEncryptAlgoEnum returns new OptKeyEncryptAlgoEnum with value set to v.
func NewOptKeyEncryptAlgoEnum(v KeyEncryptAlgoEnum) OptKeyEncryptAlgoEnum {
	return OptKeyEncryptAlgoEnum{
		Value: v,
		Set:   true,
	}
}

// OptKeyEncryptAlgoEnum is optional KeyEncryptAlgoEnum.
type OptKeyEncryptAlgoEnum struct {
	Value KeyEncryptAlgoEnum
	Set   bool
}

// IsSet returns true if OptKeyEncryptAlgoEnum was set.
func (o OptKeyEncryptAlgoEnum) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptKeyEncryptAlgoEnum) Reset() {
	var v KeyEncryptAlgoEnum
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptKeyEncryptAlgoEnum) SetTo(v KeyEncryptAlgoEnum) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptKeyEncryptAlgoEnum) Get() (v KeyEncryptAlgoEnum, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptKeyEncryptAlgoEnum) Or(d KeyEncryptAlgoEnum) KeyEncryptAlgoEnum {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptKeyServiceClassEnum returns new OptKeyServiceClassEnum with value set to v.
func NewOptKeyServiceClassEnum(v KeyServiceClassEnum) OptKeyServiceClassEnum {
	return OptKeyServiceClassEnum{
		Value: v,
		Set:   true,
	}
}

// OptKeyServiceClassEnum is optional KeyServiceClassEnum.
type OptKeyServiceClassEnum struct {
	Value KeyServiceClassEnum
	Set   bool
}

// IsSet returns true if OptKeyServiceClassEnum was set.
func (o OptKeyServiceClassEnum) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptKeyServiceClassEnum) Reset() {
	var v KeyServiceClassEnum
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptKeyServiceClassEnum) SetTo(v KeyServiceClassEnum) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptKeyServiceClassEnum) Get() (v KeyServiceClassEnum, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptKeyServiceClassEnum) Or(d KeyServiceClassEnum) KeyServiceClassEnum {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PaginatedCloudHSMClientList
type PaginatedCloudHSMClientList struct {
	Count   int              `json:"Count"`
	From    OptInt           `json:"From"`
	Total   OptInt           `json:"Total"`
	Clients []CloudHSMClient `json:"Clients"`
}

// GetCount returns the value of Count.
func (s *PaginatedCloudHSMClientList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedCloudHSMClientList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedCloudHSMClientList) GetTotal() OptInt {
	return s.Total
}

// GetClients returns the value of Clients.
func (s *PaginatedCloudHSMClientList) GetClients() []CloudHSMClient {
	return s.Clients
}

// SetCount sets the value of Count.
func (s *PaginatedCloudHSMClientList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedCloudHSMClientList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedCloudHSMClientList) SetTotal(val OptInt) {
	s.Total = val
}

// SetClients sets the value of Clients.
func (s *PaginatedCloudHSMClientList) SetClients(val []CloudHSMClient) {
	s.Clients = val
}

// Ref: #/components/schemas/PaginatedCloudHSMList
type PaginatedCloudHSMList struct {
	Count     int        `json:"Count"`
	From      OptInt     `json:"From"`
	Total     OptInt     `json:"Total"`
	CloudHSMs []CloudHSM `json:"CloudHSMs"`
}

// GetCount returns the value of Count.
func (s *PaginatedCloudHSMList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedCloudHSMList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedCloudHSMList) GetTotal() OptInt {
	return s.Total
}

// GetCloudHSMs returns the value of CloudHSMs.
func (s *PaginatedCloudHSMList) GetCloudHSMs() []CloudHSM {
	return s.CloudHSMs
}

// SetCount sets the value of Count.
func (s *PaginatedCloudHSMList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedCloudHSMList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedCloudHSMList) SetTotal(val OptInt) {
	s.Total = val
}

// SetCloudHSMs sets the value of CloudHSMs.
func (s *PaginatedCloudHSMList) SetCloudHSMs(val []CloudHSM) {
	s.CloudHSMs = val
}

// Ref: #/components/schemas/PaginatedCloudHSMSoftwareLicenseList
type PaginatedCloudHSMSoftwareLicenseList struct {
	Count     int                       `json:"Count"`
	From      OptInt                    `json:"From"`
	Total     OptInt                    `json:"Total"`
	CloudHSMs []CloudHSMSoftwareLicense `json:"CloudHSMs"`
}

// GetCount returns the value of Count.
func (s *PaginatedCloudHSMSoftwareLicenseList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedCloudHSMSoftwareLicenseList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedCloudHSMSoftwareLicenseList) GetTotal() OptInt {
	return s.Total
}

// GetCloudHSMs returns the value of CloudHSMs.
func (s *PaginatedCloudHSMSoftwareLicenseList) GetCloudHSMs() []CloudHSMSoftwareLicense {
	return s.CloudHSMs
}

// SetCount sets the value of Count.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetTotal(val OptInt) {
	s.Total = val
}

// SetCloudHSMs sets the value of CloudHSMs.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetCloudHSMs(val []CloudHSMSoftwareLicense) {
	s.CloudHSMs = val
}

// Ref: #/components/schemas/PaginatedKeyList
type PaginatedKeyList struct {
	Count int    `json:"Count"`
	From  OptInt `json:"From"`
	Total OptInt `json:"Total"`
	Keys  []Key  `json:"Keys"`
}

// GetCount returns the value of Count.
func (s *PaginatedKeyList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedKeyList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedKeyList) GetTotal() OptInt {
	return s.Total
}

// GetKeys returns the value of Keys.
func (s *PaginatedKeyList) GetKeys() []Key {
	return s.Keys
}

// SetCount sets the value of Count.
func (s *PaginatedKeyList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedKeyList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedKeyList) SetTotal(val OptInt) {
	s.Total = val
}

// SetKeys sets the value of Keys.
func (s *PaginatedKeyList) SetKeys(val []Key) {
	s.Keys = val
}

// Ref: #/components/schemas/PaginatedSecretList
type PaginatedSecretList struct {
	Count   int      `json:"Count"`
	From    OptInt   `json:"From"`
	Total   OptInt   `json:"Total"`
	Secrets []Secret `json:"Secrets"`
}

// GetCount returns the value of Count.
func (s *PaginatedSecretList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedSecretList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedSecretList) GetTotal() OptInt {
	return s.Total
}

// GetSecrets returns the value of Secrets.
func (s *PaginatedSecretList) GetSecrets() []Secret {
	return s.Secrets
}

// SetCount sets the value of Count.
func (s *PaginatedSecretList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedSecretList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedSecretList) SetTotal(val OptInt) {
	s.Total = val
}

// SetSecrets sets the value of Secrets.
func (s *PaginatedSecretList) SetSecrets(val []Secret) {
	s.Secrets = val
}

// Ref: #/components/schemas/PaginatedVaultList
type PaginatedVaultList struct {
	Count  int     `json:"Count"`
	From   OptInt  `json:"From"`
	Total  OptInt  `json:"Total"`
	Vaults []Vault `json:"Vaults"`
}

// GetCount returns the value of Count.
func (s *PaginatedVaultList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedVaultList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedVaultList) GetTotal() OptInt {
	return s.Total
}

// GetVaults returns the value of Vaults.
func (s *PaginatedVaultList) GetVaults() []Vault {
	return s.Vaults
}

// SetCount sets the value of Count.
func (s *PaginatedVaultList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedVaultList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedVaultList) SetTotal(val OptInt) {
	s.Total = val
}

// SetVaults sets the value of Vaults.
func (s *PaginatedVaultList) SetVaults(val []Vault) {
	s.Vaults = val
}

// Ref: #/components/schemas/ScheduleDestructionKey
type ScheduleDestructionKey struct {
	// 鍵を削除するまでの猶予期間を日数で指定します。
	// 7日から14日を指定できます。実際に削除されるのはこの予定時刻よりも後ろになります。.
	PendingDays int `json:"PendingDays"`
}

// GetPendingDays returns the value of PendingDays.
func (s *ScheduleDestructionKey) GetPendingDays() int {
	return s.PendingDays
}

// SetPendingDays sets the value of PendingDays.
func (s *ScheduleDestructionKey) SetPendingDays(val int) {
	s.PendingDays = val
}

// Ref: #/components/schemas/Secret
type Secret struct {
	Name          string `json:"Name"`
	LatestVersion int    `json:"LatestVersion"`
}

// GetName returns the value of Name.
func (s *Secret) GetName() string {
	return s.Name
}

// GetLatestVersion returns the value of LatestVersion.
func (s *Secret) GetLatestVersion() int {
	return s.LatestVersion
}

// SetName sets the value of Name.
func (s *Secret) SetName(val string) {
	s.Name = val
}

// SetLatestVersion sets the value of LatestVersion.
func (s *Secret) SetLatestVersion(val int) {
	s.LatestVersion = val
}

// SecretmanagerVaultsDestroyNoContent is response for SecretmanagerVaultsDestroy operation.
type SecretmanagerVaultsDestroyNoContent struct{}

// SecretmanagerVaultsSecretsDestroyNoContent is response for SecretmanagerVaultsSecretsDestroy operation.
type SecretmanagerVaultsSecretsDestroyNoContent struct{}

// * `cloud/cloudhsm/partition` - Type-L7.
// Ref: #/components/schemas/ServiceClassEnum
type ServiceClassEnum string

const (
	ServiceClassEnumCloudCloudhsmPartition ServiceClassEnum = "cloud/cloudhsm/partition"
)

// AllValues returns all ServiceClassEnum values.
func (ServiceClassEnum) AllValues() []ServiceClassEnum {
	return []ServiceClassEnum{
		ServiceClassEnumCloudCloudhsmPartition,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ServiceClassEnum) MarshalText() ([]byte, error) {
	switch s {
	case ServiceClassEnumCloudCloudhsmPartition:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ServiceClassEnum) UnmarshalText(data []byte) error {
	switch ServiceClassEnum(data) {
	case ServiceClassEnumCloudCloudhsmPartition:
		*s = ServiceClassEnumCloudCloudhsmPartition
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Unvail
type Unvail struct {
	Name    string    `json:"Name"`
	Version OptNilInt `json:"Version"`
	Value   string    `json:"Value"`
}

// GetName returns the value of Name.
func (s *Unvail) GetName() string {
	return s.Name
}

// GetVersion returns the value of Version.
func (s *Unvail) GetVersion() OptNilInt {
	return s.Version
}

// GetValue returns the value of Value.
func (s *Unvail) GetValue() string {
	return s.Value
}

// SetName sets the value of Name.
func (s *Unvail) SetName(val string) {
	s.Name = val
}

// SetVersion sets the value of Version.
func (s *Unvail) SetVersion(val OptNilInt) {
	s.Version = val
}

// SetValue sets the value of Value.
func (s *Unvail) SetValue(val string) {
	s.Value = val
}

// Ref: #/components/schemas/Vault
type Vault struct {
	ID          string    `json:"ID"`
	CreatedAt   DateTime  `json:"CreatedAt"`
	ModifiedAt  DateTime  `json:"ModifiedAt"`
	Name        string    `json:"Name"`
	Description OptString `json:"Description"`
	KmsKeyID    string    `json:"KmsKeyID"`
	Tags        []string  `json:"Tags"`
}

// GetID returns the value of ID.
func (s *Vault) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Vault) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *Vault) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetName returns the value of Name.
func (s *Vault) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Vault) GetDescription() OptString {
	return s.Description
}

// GetKmsKeyID returns the value of KmsKeyID.
func (s *Vault) GetKmsKeyID() string {
	return s.KmsKeyID
}

// GetTags returns the value of Tags.
func (s *Vault) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *Vault) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Vault) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *Vault) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetName sets the value of Name.
func (s *Vault) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Vault) SetDescription(val OptString) {
	s.Description = val
}

// SetKmsKeyID sets the value of KmsKeyID.
func (s *Vault) SetKmsKeyID(val string) {
	s.KmsKeyID = val
}

// SetTags sets the value of Tags.
func (s *Vault) SetTags(val []string) {
	s.Tags = val
}

// Ref: #/components/schemas/WrappedChangeKeyStatus
type WrappedChangeKeyStatus struct {
	Key ChangeKeyStatus `json:"Key"`
}

// GetKey returns the value of Key.
func (s *WrappedChangeKeyStatus) GetKey() ChangeKeyStatus {
	return s.Key
}

// SetKey sets the value of Key.
func (s *WrappedChangeKeyStatus) SetKey(val ChangeKeyStatus) {
	s.Key = val
}

// Ref: #/components/schemas/WrappedCloudHSM
type WrappedCloudHSM struct {
	CloudHSM CloudHSM `json:"CloudHSM"`
}

// GetCloudHSM returns the value of CloudHSM.
func (s *WrappedCloudHSM) GetCloudHSM() CloudHSM {
	return s.CloudHSM
}

// SetCloudHSM sets the value of CloudHSM.
func (s *WrappedCloudHSM) SetCloudHSM(val CloudHSM) {
	s.CloudHSM = val
}

// Ref: #/components/schemas/WrappedCloudHSMClient
type WrappedCloudHSMClient struct {
	Client CloudHSMClient `json:"Client"`
}

// GetClient returns the value of Client.
func (s *WrappedCloudHSMClient) GetClient() CloudHSMClient {
	return s.Client
}

// SetClient sets the value of Client.
func (s *WrappedCloudHSMClient) SetClient(val CloudHSMClient) {
	s.Client = val
}

// Ref: #/components/schemas/WrappedCloudHSMPeer
type WrappedCloudHSMPeer struct {
	Peer CloudHSMPeer `json:"Peer"`
}

// GetPeer returns the value of Peer.
func (s *WrappedCloudHSMPeer) GetPeer() CloudHSMPeer {
	return s.Peer
}

// SetPeer sets the value of Peer.
func (s *WrappedCloudHSMPeer) SetPeer(val CloudHSMPeer) {
	s.Peer = val
}

// Ref: #/components/schemas/WrappedCloudHSMSoftwareLicense
type WrappedCloudHSMSoftwareLicense struct {
	CloudHSM CloudHSMSoftwareLicense `json:"CloudHSM"`
}

// GetCloudHSM returns the value of CloudHSM.
func (s *WrappedCloudHSMSoftwareLicense) GetCloudHSM() CloudHSMSoftwareLicense {
	return s.CloudHSM
}

// SetCloudHSM sets the value of CloudHSM.
func (s *WrappedCloudHSMSoftwareLicense) SetCloudHSM(val CloudHSMSoftwareLicense) {
	s.CloudHSM = val
}

// Ref: #/components/schemas/WrappedCreateCloudHSM
type WrappedCreateCloudHSM struct {
	CloudHSM CreateCloudHSM `json:"CloudHSM"`
}

// GetCloudHSM returns the value of CloudHSM.
func (s *WrappedCreateCloudHSM) GetCloudHSM() CreateCloudHSM {
	return s.CloudHSM
}

// SetCloudHSM sets the value of CloudHSM.
func (s *WrappedCreateCloudHSM) SetCloudHSM(val CreateCloudHSM) {
	s.CloudHSM = val
}

// Ref: #/components/schemas/WrappedCreateCloudHSMClient
type WrappedCreateCloudHSMClient struct {
	Client CreateCloudHSMClient `json:"Client"`
}

// GetClient returns the value of Client.
func (s *WrappedCreateCloudHSMClient) GetClient() CreateCloudHSMClient {
	return s.Client
}

// SetClient sets the value of Client.
func (s *WrappedCreateCloudHSMClient) SetClient(val CreateCloudHSMClient) {
	s.Client = val
}

// Ref: #/components/schemas/WrappedCreateCloudHSMPeer
type WrappedCreateCloudHSMPeer struct {
	Peer CreateCloudHSMPeer `json:"Peer"`
}

// GetPeer returns the value of Peer.
func (s *WrappedCreateCloudHSMPeer) GetPeer() CreateCloudHSMPeer {
	return s.Peer
}

// SetPeer sets the value of Peer.
func (s *WrappedCreateCloudHSMPeer) SetPeer(val CreateCloudHSMPeer) {
	s.Peer = val
}

// Ref: #/components/schemas/WrappedCreateCloudHSMSoftwareLicense
type WrappedCreateCloudHSMSoftwareLicense struct {
	CloudHSM CreateCloudHSMSoftwareLicense `json:"CloudHSM"`
}

// GetCloudHSM returns the value of CloudHSM.
func (s *WrappedCreateCloudHSMSoftwareLicense) GetCloudHSM() CreateCloudHSMSoftwareLicense {
	return s.CloudHSM
}

// SetCloudHSM sets the value of CloudHSM.
func (s *WrappedCreateCloudHSMSoftwareLicense) SetCloudHSM(val CreateCloudHSMSoftwareLicense) {
	s.CloudHSM = val
}

// Ref: #/components/schemas/WrappedCreateKey
type WrappedCreateKey struct {
	Key CreateKey `json:"Key"`
}

// GetKey returns the value of Key.
func (s *WrappedCreateKey) GetKey() CreateKey {
	return s.Key
}

// SetKey sets the value of Key.
func (s *WrappedCreateKey) SetKey(val CreateKey) {
	s.Key = val
}

// Ref: #/components/schemas/WrappedCreateSecret
type WrappedCreateSecret struct {
	Secret CreateSecret `json:"Secret"`
}

// GetSecret returns the value of Secret.
func (s *WrappedCreateSecret) GetSecret() CreateSecret {
	return s.Secret
}

// SetSecret sets the value of Secret.
func (s *WrappedCreateSecret) SetSecret(val CreateSecret) {
	s.Secret = val
}

// Ref: #/components/schemas/WrappedCreateVault
type WrappedCreateVault struct {
	Vault CreateVault `json:"Vault"`
}

// GetVault returns the value of Vault.
func (s *WrappedCreateVault) GetVault() CreateVault {
	return s.Vault
}

// SetVault sets the value of Vault.
func (s *WrappedCreateVault) SetVault(val CreateVault) {
	s.Vault = val
}

// Ref: #/components/schemas/WrappedDeleteSecret
type WrappedDeleteSecret struct {
	Secret DeleteSecret `json:"Secret"`
}

// GetSecret returns the value of Secret.
func (s *WrappedDeleteSecret) GetSecret() DeleteSecret {
	return s.Secret
}

// SetSecret sets the value of Secret.
func (s *WrappedDeleteSecret) SetSecret(val DeleteSecret) {
	s.Secret = val
}

// Ref: #/components/schemas/WrappedKey
type WrappedKey struct {
	Key Key `json:"Key"`
}

// GetKey returns the value of Key.
func (s *WrappedKey) GetKey() Key {
	return s.Key
}

// SetKey sets the value of Key.
func (s *WrappedKey) SetKey(val Key) {
	s.Key = val
}

func (*WrappedKey) kmsKeysRotateRes() {}

// Ref: #/components/schemas/WrappedKeyCipher
type WrappedKeyCipher struct {
	Key KeyCipher `json:"Key"`
}

// GetKey returns the value of Key.
func (s *WrappedKeyCipher) GetKey() KeyCipher {
	return s.Key
}

// SetKey sets the value of Key.
func (s *WrappedKeyCipher) SetKey(val KeyCipher) {
	s.Key = val
}

// Ref: #/components/schemas/WrappedKeyPlain
type WrappedKeyPlain struct {
	Key KeyPlain `json:"Key"`
}

// GetKey returns the value of Key.
func (s *WrappedKeyPlain) GetKey() KeyPlain {
	return s.Key
}

// SetKey sets the value of Key.
func (s *WrappedKeyPlain) SetKey(val KeyPlain) {
	s.Key = val
}

// Ref: #/components/schemas/WrappedScheduleDestructionKey
type WrappedScheduleDestructionKey struct {
	Key ScheduleDestructionKey `json:"Key"`
}

// GetKey returns the value of Key.
func (s *WrappedScheduleDestructionKey) GetKey() ScheduleDestructionKey {
	return s.Key
}

// SetKey sets the value of Key.
func (s *WrappedScheduleDestructionKey) SetKey(val ScheduleDestructionKey) {
	s.Key = val
}

// Ref: #/components/schemas/WrappedUnvail
type WrappedUnvail struct {
	Secret Unvail `json:"Secret"`
}

// GetSecret returns the value of Secret.
func (s *WrappedUnvail) GetSecret() Unvail {
	return s.Secret
}

// SetSecret sets the value of Secret.
func (s *WrappedUnvail) SetSecret(val Unvail) {
	s.Secret = val
}

// Ref: #/components/schemas/WrappedVault
type WrappedVault struct {
	Vault Vault `json:"Vault"`
}

// GetVault returns the value of Vault.
func (s *WrappedVault) GetVault() Vault {
	return s.Vault
}

// SetVault sets the value of Vault.
func (s *WrappedVault) SetVault(val Vault) {
	s.Vault = val
}
