// Code generated by ogen, DO NOT EDIT.

package v1

// CloudhsmCloudhsmsClientsCreateParams is parameters of cloudhsm_cloudhsms_clients_create operation.
type CloudhsmCloudhsmsClientsCreateParams struct {
	CloudhsmResourceID string
}

// CloudhsmCloudhsmsClientsDestroyParams is parameters of cloudhsm_cloudhsms_clients_destroy operation.
type CloudhsmCloudhsmsClientsDestroyParams struct {
	CloudhsmResourceID string
	// A unique value identifying this CloudHSMクライアント.
	ID string
}

// CloudhsmCloudhsmsClientsListParams is parameters of cloudhsm_cloudhsms_clients_list operation.
type CloudhsmCloudhsmsClientsListParams struct {
	CloudhsmResourceID string
}

// CloudhsmCloudhsmsClientsRetrieveParams is parameters of cloudhsm_cloudhsms_clients_retrieve operation.
type CloudhsmCloudhsmsClientsRetrieveParams struct {
	CloudhsmResourceID string
	// A unique value identifying this CloudHSMクライアント.
	ID string
}

// CloudhsmCloudhsmsClientsUpdateParams is parameters of cloudhsm_cloudhsms_clients_update operation.
type CloudhsmCloudhsmsClientsUpdateParams struct {
	CloudhsmResourceID string
	// A unique value identifying this CloudHSMクライアント.
	ID string
}

// CloudhsmCloudhsmsDestroyParams is parameters of cloudhsm_cloudhsms_destroy operation.
type CloudhsmCloudhsmsDestroyParams struct {
	ResourceID string
}

// CloudhsmCloudhsmsPeersCreateParams is parameters of cloudhsm_cloudhsms_peers_create operation.
type CloudhsmCloudhsmsPeersCreateParams struct {
	ResourceID string
}

// CloudhsmCloudhsmsPeersDestroyParams is parameters of cloudhsm_cloudhsms_peers_destroy operation.
type CloudhsmCloudhsmsPeersDestroyParams struct {
	PeerID     string
	ResourceID string
}

// CloudhsmCloudhsmsPeersRetrieveParams is parameters of cloudhsm_cloudhsms_peers_retrieve operation.
type CloudhsmCloudhsmsPeersRetrieveParams struct {
	ResourceID string
}

// CloudhsmCloudhsmsRetrieveParams is parameters of cloudhsm_cloudhsms_retrieve operation.
type CloudhsmCloudhsmsRetrieveParams struct {
	ResourceID string
}

// CloudhsmCloudhsmsUpdateParams is parameters of cloudhsm_cloudhsms_update operation.
type CloudhsmCloudhsmsUpdateParams struct {
	ResourceID string
}

// CloudhsmLicensesDestroyParams is parameters of cloudhsm_licenses_destroy operation.
type CloudhsmLicensesDestroyParams struct {
	ResourceID string
}

// CloudhsmLicensesRetrieveParams is parameters of cloudhsm_licenses_retrieve operation.
type CloudhsmLicensesRetrieveParams struct {
	ResourceID string
}

// CloudhsmLicensesUpdateParams is parameters of cloudhsm_licenses_update operation.
type CloudhsmLicensesUpdateParams struct {
	ResourceID string
}

// KmsKeysDecryptParams is parameters of kms_keys_decrypt operation.
type KmsKeysDecryptParams struct {
	ResourceID string
}

// KmsKeysDestroyParams is parameters of kms_keys_destroy operation.
type KmsKeysDestroyParams struct {
	ResourceID string
}

// KmsKeysEncryptParams is parameters of kms_keys_encrypt operation.
type KmsKeysEncryptParams struct {
	ResourceID string
}

// KmsKeysRetrieveParams is parameters of kms_keys_retrieve operation.
type KmsKeysRetrieveParams struct {
	ResourceID string
}

// KmsKeysRotateParams is parameters of kms_keys_rotate operation.
type KmsKeysRotateParams struct {
	ResourceID string
}

// KmsKeysScheduleDestructionParams is parameters of kms_keys_schedule_destruction operation.
type KmsKeysScheduleDestructionParams struct {
	ResourceID string
}

// KmsKeysStatusParams is parameters of kms_keys_status operation.
type KmsKeysStatusParams struct {
	ResourceID string
}

// KmsKeysUpdateParams is parameters of kms_keys_update operation.
type KmsKeysUpdateParams struct {
	ResourceID string
}

// SecretmanagerVaultsDestroyParams is parameters of secretmanager_vaults_destroy operation.
type SecretmanagerVaultsDestroyParams struct {
	ResourceID string
}

// SecretmanagerVaultsRetrieveParams is parameters of secretmanager_vaults_retrieve operation.
type SecretmanagerVaultsRetrieveParams struct {
	ResourceID string
}

// SecretmanagerVaultsSecretsCreateParams is parameters of secretmanager_vaults_secrets_create operation.
type SecretmanagerVaultsSecretsCreateParams struct {
	VaultResourceID string
}

// SecretmanagerVaultsSecretsDestroyParams is parameters of secretmanager_vaults_secrets_destroy operation.
type SecretmanagerVaultsSecretsDestroyParams struct {
	VaultResourceID string
}

// SecretmanagerVaultsSecretsListParams is parameters of secretmanager_vaults_secrets_list operation.
type SecretmanagerVaultsSecretsListParams struct {
	VaultResourceID string
}

// SecretmanagerVaultsSecretsUnveilParams is parameters of secretmanager_vaults_secrets_unveil operation.
type SecretmanagerVaultsSecretsUnveilParams struct {
	VaultResourceID string
}

// SecretmanagerVaultsUpdateParams is parameters of secretmanager_vaults_update operation.
type SecretmanagerVaultsUpdateParams struct {
	ResourceID string
}
