// Code generated by ogen, DO NOT EDIT.

package v1

// SetFake set fake values.
func (s *AvailabilityEnum) SetFake() {
	*s = AvailabilityEnumPrecreate
}

// SetFake set fake values.
func (s *ChangeKeyStatus) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ChangeKeyStatusStatus) SetFake() {
	*s = ChangeKeyStatusStatusActive
}

// SetFake set fake values.
func (s *CloudHSM) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.IPv4NetworkAddress = "string"
		}
	}
	{
		{
			s.IPv4PrefixLength = int(0)
		}
	}
	{
		{
			s.IPv4Address = "string"
		}
	}
	{
		{
			s.LocalRouter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMClient) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Certificate = "string"
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMLocalRouter) SetFake() {
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.SecretKey.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMPeer) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.SecretKey = "string"
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMPeerList) SetFake() {
	{
		{
			s.Peers = nil
			for i := 0; i < 0; i++ {
				var elem CloudHSMPeer
				{
					elem.SetFake()
				}
				s.Peers = append(s.Peers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMSoftwareLicense) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description = "string"
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CloudHSMSoftwareLicenseServiceClassEnum) SetFake() {
	*s = CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7
}

// SetFake set fake values.
func (s *CreateCloudHSM) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.IPv4NetworkAddress = "string"
		}
	}
	{
		{
			s.IPv4PrefixLength = int(0)
		}
	}
	{
		{
			s.IPv4Address = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateCloudHSMClient) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Certificate = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateCloudHSMPeer) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.SecretKey = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateCloudHSMSoftwareLicense) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateKey) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.KeyOrigin.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.PlainKey.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateSecret) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
	{
		{
			s.LatestVersion = int(0)
		}
	}
}

// SetFake set fake values.
func (s *CreateVault) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.KmsKeyID = "string"
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *DateTime) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = DateTime(unwrapped)
}

// SetFake set fake values.
func (s *DeleteSecret) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *Key) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description = "string"
		}
	}
	{
		{
			s.KeyOrigin.SetFake()
		}
	}
	{
		{
			s.LatestVersion.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *KeyCipher) SetFake() {
	{
		{
			s.Cipher = "string"
		}
	}
}

// SetFake set fake values.
func (s *KeyEncryptAlgoEnum) SetFake() {
	*s = KeyEncryptAlgoEnumAes256Gcm
}

// SetFake set fake values.
func (s *KeyOriginEnum) SetFake() {
	*s = KeyOriginEnumGenerated
}

// SetFake set fake values.
func (s *KeyPlain) SetFake() {
	{
		{
			s.Plain = "string"
		}
	}
	{
		{
			s.Algo.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *KeyServiceClassEnum) SetFake() {
	*s = KeyServiceClassEnumCloudKmsKey
}

// SetFake set fake values.
func (s *KeyStatusEnum) SetFake() {
	*s = KeyStatusEnumActive
}

// SetFake set fake values.
func (s *NilCloudHSMLocalRouter) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *OptChangeKeyStatusStatus) SetFake() {
	var elem ChangeKeyStatusStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptKeyEncryptAlgoEnum) SetFake() {
	var elem KeyEncryptAlgoEnum
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptKeyServiceClassEnum) SetFake() {
	var elem KeyServiceClassEnum
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilInt) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *PaginatedCloudHSMClientList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.Clients = nil
			for i := 0; i < 0; i++ {
				var elem CloudHSMClient
				{
					elem.SetFake()
				}
				s.Clients = append(s.Clients, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedCloudHSMList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.CloudHSMs = nil
			for i := 0; i < 0; i++ {
				var elem CloudHSM
				{
					elem.SetFake()
				}
				s.CloudHSMs = append(s.CloudHSMs, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.CloudHSMs = nil
			for i := 0; i < 0; i++ {
				var elem CloudHSMSoftwareLicense
				{
					elem.SetFake()
				}
				s.CloudHSMs = append(s.CloudHSMs, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedKeyList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.Keys = nil
			for i := 0; i < 0; i++ {
				var elem Key
				{
					elem.SetFake()
				}
				s.Keys = append(s.Keys, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedSecretList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.Secrets = nil
			for i := 0; i < 0; i++ {
				var elem Secret
				{
					elem.SetFake()
				}
				s.Secrets = append(s.Secrets, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PaginatedVaultList) SetFake() {
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.Vaults = nil
			for i := 0; i < 0; i++ {
				var elem Vault
				{
					elem.SetFake()
				}
				s.Vaults = append(s.Vaults, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ScheduleDestructionKey) SetFake() {
	{
		{
			s.PendingDays = int(0)
		}
	}
}

// SetFake set fake values.
func (s *Secret) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.LatestVersion = int(0)
		}
	}
}

// SetFake set fake values.
func (s *ServiceClassEnum) SetFake() {
	*s = ServiceClassEnumCloudCloudhsmPartition
}

// SetFake set fake values.
func (s *Unvail) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Version.SetFake()
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *Vault) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.ModifiedAt.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.KmsKeyID = "string"
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *WrappedChangeKeyStatus) SetFake() {
	{
		{
			s.Key.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCloudHSM) SetFake() {
	{
		{
			s.CloudHSM.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCloudHSMClient) SetFake() {
	{
		{
			s.Client.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCloudHSMPeer) SetFake() {
	{
		{
			s.Peer.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCloudHSMSoftwareLicense) SetFake() {
	{
		{
			s.CloudHSM.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateCloudHSM) SetFake() {
	{
		{
			s.CloudHSM.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateCloudHSMClient) SetFake() {
	{
		{
			s.Client.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateCloudHSMPeer) SetFake() {
	{
		{
			s.Peer.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateCloudHSMSoftwareLicense) SetFake() {
	{
		{
			s.CloudHSM.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateKey) SetFake() {
	{
		{
			s.Key.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateSecret) SetFake() {
	{
		{
			s.Secret.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedCreateVault) SetFake() {
	{
		{
			s.Vault.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedDeleteSecret) SetFake() {
	{
		{
			s.Secret.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedKey) SetFake() {
	{
		{
			s.Key.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedKeyCipher) SetFake() {
	{
		{
			s.Key.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedKeyPlain) SetFake() {
	{
		{
			s.Key.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedScheduleDestructionKey) SetFake() {
	{
		{
			s.Key.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedUnvail) SetFake() {
	{
		{
			s.Secret.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *WrappedVault) SetFake() {
	{
		{
			s.Vault.SetFake()
		}
	}
}
