// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"github.com/go-faster/errors"
)

// * `precreate` - 準備中
// * `available` - 利用可能
// * `discontinued` - 廃止.
// Ref: #/components/schemas/AvailabilityEnum
type AvailabilityEnum string

const (
	AvailabilityEnumPrecreate    AvailabilityEnum = "precreate"
	AvailabilityEnumAvailable    AvailabilityEnum = "available"
	AvailabilityEnumDiscontinued AvailabilityEnum = "discontinued"
)

// AllValues returns all AvailabilityEnum values.
func (AvailabilityEnum) AllValues() []AvailabilityEnum {
	return []AvailabilityEnum{
		AvailabilityEnumPrecreate,
		AvailabilityEnumAvailable,
		AvailabilityEnumDiscontinued,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AvailabilityEnum) MarshalText() ([]byte, error) {
	switch s {
	case AvailabilityEnumPrecreate:
		return []byte(s), nil
	case AvailabilityEnumAvailable:
		return []byte(s), nil
	case AvailabilityEnumDiscontinued:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AvailabilityEnum) UnmarshalText(data []byte) error {
	switch AvailabilityEnum(data) {
	case AvailabilityEnumPrecreate:
		*s = AvailabilityEnumPrecreate
		return nil
	case AvailabilityEnumAvailable:
		*s = AvailabilityEnumAvailable
		return nil
	case AvailabilityEnumDiscontinued:
		*s = AvailabilityEnumDiscontinued
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BasicAuth struct {
	Username string
	Password string
	Roles    []string
}

// GetUsername returns the value of Username.
func (s *BasicAuth) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *BasicAuth) GetPassword() string {
	return s.Password
}

// GetRoles returns the value of Roles.
func (s *BasicAuth) GetRoles() []string {
	return s.Roles
}

// SetUsername sets the value of Username.
func (s *BasicAuth) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *BasicAuth) SetPassword(val string) {
	s.Password = val
}

// SetRoles sets the value of Roles.
func (s *BasicAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CloudHSM
type CloudHSM struct {
	ID                 string                 `json:"ID"`
	CreatedAt          DateTime               `json:"CreatedAt"`
	ModifiedAt         DateTime               `json:"ModifiedAt"`
	ServiceClass       ServiceClassEnum       `json:"ServiceClass"`
	Availability       AvailabilityEnum       `json:"Availability"`
	Name               string                 `json:"Name"`
	Description        OptString              `json:"Description"`
	Tags               []string               `json:"Tags"`
	IPv4NetworkAddress string                 `json:"IPv4NetworkAddress"`
	IPv4PrefixLength   int                    `json:"IPv4PrefixLength"`
	IPv4Address        string                 `json:"IPv4Address"`
	LocalRouter        NilCloudHSMLocalRouter `json:"LocalRouter"`
}

// GetID returns the value of ID.
func (s *CloudHSM) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CloudHSM) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CloudHSM) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *CloudHSM) GetServiceClass() ServiceClassEnum {
	return s.ServiceClass
}

// GetAvailability returns the value of Availability.
func (s *CloudHSM) GetAvailability() AvailabilityEnum {
	return s.Availability
}

// GetName returns the value of Name.
func (s *CloudHSM) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CloudHSM) GetDescription() OptString {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *CloudHSM) GetTags() []string {
	return s.Tags
}

// GetIPv4NetworkAddress returns the value of IPv4NetworkAddress.
func (s *CloudHSM) GetIPv4NetworkAddress() string {
	return s.IPv4NetworkAddress
}

// GetIPv4PrefixLength returns the value of IPv4PrefixLength.
func (s *CloudHSM) GetIPv4PrefixLength() int {
	return s.IPv4PrefixLength
}

// GetIPv4Address returns the value of IPv4Address.
func (s *CloudHSM) GetIPv4Address() string {
	return s.IPv4Address
}

// GetLocalRouter returns the value of LocalRouter.
func (s *CloudHSM) GetLocalRouter() NilCloudHSMLocalRouter {
	return s.LocalRouter
}

// SetID sets the value of ID.
func (s *CloudHSM) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CloudHSM) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CloudHSM) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CloudHSM) SetServiceClass(val ServiceClassEnum) {
	s.ServiceClass = val
}

// SetAvailability sets the value of Availability.
func (s *CloudHSM) SetAvailability(val AvailabilityEnum) {
	s.Availability = val
}

// SetName sets the value of Name.
func (s *CloudHSM) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CloudHSM) SetDescription(val OptString) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *CloudHSM) SetTags(val []string) {
	s.Tags = val
}

// SetIPv4NetworkAddress sets the value of IPv4NetworkAddress.
func (s *CloudHSM) SetIPv4NetworkAddress(val string) {
	s.IPv4NetworkAddress = val
}

// SetIPv4PrefixLength sets the value of IPv4PrefixLength.
func (s *CloudHSM) SetIPv4PrefixLength(val int) {
	s.IPv4PrefixLength = val
}

// SetIPv4Address sets the value of IPv4Address.
func (s *CloudHSM) SetIPv4Address(val string) {
	s.IPv4Address = val
}

// SetLocalRouter sets the value of LocalRouter.
func (s *CloudHSM) SetLocalRouter(val NilCloudHSMLocalRouter) {
	s.LocalRouter = val
}

// Ref: #/components/schemas/CloudHSMClient
type CloudHSMClient struct {
	ID           string           `json:"ID"`
	CreatedAt    DateTime         `json:"CreatedAt"`
	ModifiedAt   DateTime         `json:"ModifiedAt"`
	Availability AvailabilityEnum `json:"Availability"`
	Name         string           `json:"Name"`
	Certificate  string           `json:"Certificate"`
}

// GetID returns the value of ID.
func (s *CloudHSMClient) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CloudHSMClient) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CloudHSMClient) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetAvailability returns the value of Availability.
func (s *CloudHSMClient) GetAvailability() AvailabilityEnum {
	return s.Availability
}

// GetName returns the value of Name.
func (s *CloudHSMClient) GetName() string {
	return s.Name
}

// GetCertificate returns the value of Certificate.
func (s *CloudHSMClient) GetCertificate() string {
	return s.Certificate
}

// SetID sets the value of ID.
func (s *CloudHSMClient) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CloudHSMClient) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CloudHSMClient) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetAvailability sets the value of Availability.
func (s *CloudHSMClient) SetAvailability(val AvailabilityEnum) {
	s.Availability = val
}

// SetName sets the value of Name.
func (s *CloudHSMClient) SetName(val string) {
	s.Name = val
}

// SetCertificate sets the value of Certificate.
func (s *CloudHSMClient) SetCertificate(val string) {
	s.Certificate = val
}

// Ref: #/components/schemas/CloudHSMLocalRouter
type CloudHSMLocalRouter struct {
	ResourceID OptString `json:"ResourceID"`
	SecretKey  OptString `json:"SecretKey"`
}

// GetResourceID returns the value of ResourceID.
func (s *CloudHSMLocalRouter) GetResourceID() OptString {
	return s.ResourceID
}

// GetSecretKey returns the value of SecretKey.
func (s *CloudHSMLocalRouter) GetSecretKey() OptString {
	return s.SecretKey
}

// SetResourceID sets the value of ResourceID.
func (s *CloudHSMLocalRouter) SetResourceID(val OptString) {
	s.ResourceID = val
}

// SetSecretKey sets the value of SecretKey.
func (s *CloudHSMLocalRouter) SetSecretKey(val OptString) {
	s.SecretKey = val
}

// Ref: #/components/schemas/CloudHSMPeer
type CloudHSMPeer struct {
	ID        string `json:"ID"`
	SecretKey string `json:"SecretKey"`
}

// GetID returns the value of ID.
func (s *CloudHSMPeer) GetID() string {
	return s.ID
}

// GetSecretKey returns the value of SecretKey.
func (s *CloudHSMPeer) GetSecretKey() string {
	return s.SecretKey
}

// SetID sets the value of ID.
func (s *CloudHSMPeer) SetID(val string) {
	s.ID = val
}

// SetSecretKey sets the value of SecretKey.
func (s *CloudHSMPeer) SetSecretKey(val string) {
	s.SecretKey = val
}

// Ref: #/components/schemas/CloudHSMPeerList
type CloudHSMPeerList struct {
	Peers []CloudHSMPeer `json:"Peers"`
}

// GetPeers returns the value of Peers.
func (s *CloudHSMPeerList) GetPeers() []CloudHSMPeer {
	return s.Peers
}

// SetPeers sets the value of Peers.
func (s *CloudHSMPeerList) SetPeers(val []CloudHSMPeer) {
	s.Peers = val
}

// Ref: #/components/schemas/CloudHSMSoftwareLicense
type CloudHSMSoftwareLicense struct {
	ID           string                                  `json:"ID"`
	CreatedAt    DateTime                                `json:"CreatedAt"`
	ModifiedAt   DateTime                                `json:"ModifiedAt"`
	ServiceClass CloudHSMSoftwareLicenseServiceClassEnum `json:"ServiceClass"`
	Name         string                                  `json:"Name"`
	Description  string                                  `json:"Description"`
	Tags         []string                                `json:"Tags"`
}

// GetID returns the value of ID.
func (s *CloudHSMSoftwareLicense) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CloudHSMSoftwareLicense) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CloudHSMSoftwareLicense) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *CloudHSMSoftwareLicense) GetServiceClass() CloudHSMSoftwareLicenseServiceClassEnum {
	return s.ServiceClass
}

// GetName returns the value of Name.
func (s *CloudHSMSoftwareLicense) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CloudHSMSoftwareLicense) GetDescription() string {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *CloudHSMSoftwareLicense) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *CloudHSMSoftwareLicense) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CloudHSMSoftwareLicense) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CloudHSMSoftwareLicense) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CloudHSMSoftwareLicense) SetServiceClass(val CloudHSMSoftwareLicenseServiceClassEnum) {
	s.ServiceClass = val
}

// SetName sets the value of Name.
func (s *CloudHSMSoftwareLicense) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CloudHSMSoftwareLicense) SetDescription(val string) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *CloudHSMSoftwareLicense) SetTags(val []string) {
	s.Tags = val
}

// * `cloud/cloudhsm/license/l7` - for Type-L7 Client.
// Ref: #/components/schemas/CloudHSMSoftwareLicenseServiceClassEnum
type CloudHSMSoftwareLicenseServiceClassEnum string

const (
	CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7 CloudHSMSoftwareLicenseServiceClassEnum = "cloud/cloudhsm/license/l7"
)

// AllValues returns all CloudHSMSoftwareLicenseServiceClassEnum values.
func (CloudHSMSoftwareLicenseServiceClassEnum) AllValues() []CloudHSMSoftwareLicenseServiceClassEnum {
	return []CloudHSMSoftwareLicenseServiceClassEnum{
		CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CloudHSMSoftwareLicenseServiceClassEnum) MarshalText() ([]byte, error) {
	switch s {
	case CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CloudHSMSoftwareLicenseServiceClassEnum) UnmarshalText(data []byte) error {
	switch CloudHSMSoftwareLicenseServiceClassEnum(data) {
	case CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7:
		*s = CloudHSMSoftwareLicenseServiceClassEnumCloudCloudhsmLicenseL7
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// CloudhsmCloudhsmsClientsDestroyNoContent is response for CloudhsmCloudhsmsClientsDestroy operation.
type CloudhsmCloudhsmsClientsDestroyNoContent struct{}

// CloudhsmCloudhsmsDestroyNoContent is response for CloudhsmCloudhsmsDestroy operation.
type CloudhsmCloudhsmsDestroyNoContent struct{}

// CloudhsmCloudhsmsPeersDestroyNoContent is response for CloudhsmCloudhsmsPeersDestroy operation.
type CloudhsmCloudhsmsPeersDestroyNoContent struct{}

// CloudhsmLicensesDestroyNoContent is response for CloudhsmLicensesDestroy operation.
type CloudhsmLicensesDestroyNoContent struct{}

// Ref: #/components/schemas/CreateCloudHSM
type CreateCloudHSM struct {
	ID                 string           `json:"ID"`
	CreatedAt          DateTime         `json:"CreatedAt"`
	ModifiedAt         DateTime         `json:"ModifiedAt"`
	ServiceClass       ServiceClassEnum `json:"ServiceClass"`
	Availability       AvailabilityEnum `json:"Availability"`
	Name               string           `json:"Name"`
	Description        OptString        `json:"Description"`
	Tags               []string         `json:"Tags"`
	IPv4NetworkAddress string           `json:"IPv4NetworkAddress"`
	IPv4PrefixLength   int              `json:"IPv4PrefixLength"`
	IPv4Address        string           `json:"IPv4Address"`
}

// GetID returns the value of ID.
func (s *CreateCloudHSM) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateCloudHSM) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CreateCloudHSM) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *CreateCloudHSM) GetServiceClass() ServiceClassEnum {
	return s.ServiceClass
}

// GetAvailability returns the value of Availability.
func (s *CreateCloudHSM) GetAvailability() AvailabilityEnum {
	return s.Availability
}

// GetName returns the value of Name.
func (s *CreateCloudHSM) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateCloudHSM) GetDescription() OptString {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *CreateCloudHSM) GetTags() []string {
	return s.Tags
}

// GetIPv4NetworkAddress returns the value of IPv4NetworkAddress.
func (s *CreateCloudHSM) GetIPv4NetworkAddress() string {
	return s.IPv4NetworkAddress
}

// GetIPv4PrefixLength returns the value of IPv4PrefixLength.
func (s *CreateCloudHSM) GetIPv4PrefixLength() int {
	return s.IPv4PrefixLength
}

// GetIPv4Address returns the value of IPv4Address.
func (s *CreateCloudHSM) GetIPv4Address() string {
	return s.IPv4Address
}

// SetID sets the value of ID.
func (s *CreateCloudHSM) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateCloudHSM) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CreateCloudHSM) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CreateCloudHSM) SetServiceClass(val ServiceClassEnum) {
	s.ServiceClass = val
}

// SetAvailability sets the value of Availability.
func (s *CreateCloudHSM) SetAvailability(val AvailabilityEnum) {
	s.Availability = val
}

// SetName sets the value of Name.
func (s *CreateCloudHSM) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateCloudHSM) SetDescription(val OptString) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *CreateCloudHSM) SetTags(val []string) {
	s.Tags = val
}

// SetIPv4NetworkAddress sets the value of IPv4NetworkAddress.
func (s *CreateCloudHSM) SetIPv4NetworkAddress(val string) {
	s.IPv4NetworkAddress = val
}

// SetIPv4PrefixLength sets the value of IPv4PrefixLength.
func (s *CreateCloudHSM) SetIPv4PrefixLength(val int) {
	s.IPv4PrefixLength = val
}

// SetIPv4Address sets the value of IPv4Address.
func (s *CreateCloudHSM) SetIPv4Address(val string) {
	s.IPv4Address = val
}

// Ref: #/components/schemas/CreateCloudHSMClient
type CreateCloudHSMClient struct {
	ID           string           `json:"ID"`
	CreatedAt    DateTime         `json:"CreatedAt"`
	ModifiedAt   DateTime         `json:"ModifiedAt"`
	Availability AvailabilityEnum `json:"Availability"`
	Name         string           `json:"Name"`
	Certificate  string           `json:"Certificate"`
}

// GetID returns the value of ID.
func (s *CreateCloudHSMClient) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateCloudHSMClient) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CreateCloudHSMClient) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetAvailability returns the value of Availability.
func (s *CreateCloudHSMClient) GetAvailability() AvailabilityEnum {
	return s.Availability
}

// GetName returns the value of Name.
func (s *CreateCloudHSMClient) GetName() string {
	return s.Name
}

// GetCertificate returns the value of Certificate.
func (s *CreateCloudHSMClient) GetCertificate() string {
	return s.Certificate
}

// SetID sets the value of ID.
func (s *CreateCloudHSMClient) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateCloudHSMClient) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CreateCloudHSMClient) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetAvailability sets the value of Availability.
func (s *CreateCloudHSMClient) SetAvailability(val AvailabilityEnum) {
	s.Availability = val
}

// SetName sets the value of Name.
func (s *CreateCloudHSMClient) SetName(val string) {
	s.Name = val
}

// SetCertificate sets the value of Certificate.
func (s *CreateCloudHSMClient) SetCertificate(val string) {
	s.Certificate = val
}

// Ref: #/components/schemas/CreateCloudHSMPeer
type CreateCloudHSMPeer struct {
	ID        string `json:"ID"`
	SecretKey string `json:"SecretKey"`
}

// GetID returns the value of ID.
func (s *CreateCloudHSMPeer) GetID() string {
	return s.ID
}

// GetSecretKey returns the value of SecretKey.
func (s *CreateCloudHSMPeer) GetSecretKey() string {
	return s.SecretKey
}

// SetID sets the value of ID.
func (s *CreateCloudHSMPeer) SetID(val string) {
	s.ID = val
}

// SetSecretKey sets the value of SecretKey.
func (s *CreateCloudHSMPeer) SetSecretKey(val string) {
	s.SecretKey = val
}

// Ref: #/components/schemas/CreateCloudHSMSoftwareLicense
type CreateCloudHSMSoftwareLicense struct {
	ID           string                                  `json:"ID"`
	CreatedAt    DateTime                                `json:"CreatedAt"`
	ModifiedAt   DateTime                                `json:"ModifiedAt"`
	ServiceClass CloudHSMSoftwareLicenseServiceClassEnum `json:"ServiceClass"`
	Name         string                                  `json:"Name"`
	Description  OptString                               `json:"Description"`
	Tags         []string                                `json:"Tags"`
}

// GetID returns the value of ID.
func (s *CreateCloudHSMSoftwareLicense) GetID() string {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateCloudHSMSoftwareLicense) GetCreatedAt() DateTime {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CreateCloudHSMSoftwareLicense) GetModifiedAt() DateTime {
	return s.ModifiedAt
}

// GetServiceClass returns the value of ServiceClass.
func (s *CreateCloudHSMSoftwareLicense) GetServiceClass() CloudHSMSoftwareLicenseServiceClassEnum {
	return s.ServiceClass
}

// GetName returns the value of Name.
func (s *CreateCloudHSMSoftwareLicense) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateCloudHSMSoftwareLicense) GetDescription() OptString {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *CreateCloudHSMSoftwareLicense) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *CreateCloudHSMSoftwareLicense) SetID(val string) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateCloudHSMSoftwareLicense) SetCreatedAt(val DateTime) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CreateCloudHSMSoftwareLicense) SetModifiedAt(val DateTime) {
	s.ModifiedAt = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CreateCloudHSMSoftwareLicense) SetServiceClass(val CloudHSMSoftwareLicenseServiceClassEnum) {
	s.ServiceClass = val
}

// SetName sets the value of Name.
func (s *CreateCloudHSMSoftwareLicense) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateCloudHSMSoftwareLicense) SetDescription(val OptString) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *CreateCloudHSMSoftwareLicense) SetTags(val []string) {
	s.Tags = val
}

type DateTime string

// NewNilCloudHSMLocalRouter returns new NilCloudHSMLocalRouter with value set to v.
func NewNilCloudHSMLocalRouter(v CloudHSMLocalRouter) NilCloudHSMLocalRouter {
	return NilCloudHSMLocalRouter{
		Value: v,
	}
}

// NilCloudHSMLocalRouter is nullable CloudHSMLocalRouter.
type NilCloudHSMLocalRouter struct {
	Value CloudHSMLocalRouter
	Null  bool
}

// SetTo sets value to v.
func (o *NilCloudHSMLocalRouter) SetTo(v CloudHSMLocalRouter) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilCloudHSMLocalRouter) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilCloudHSMLocalRouter) SetToNull() {
	o.Null = true
	var v CloudHSMLocalRouter
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilCloudHSMLocalRouter) Get() (v CloudHSMLocalRouter, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilCloudHSMLocalRouter) Or(d CloudHSMLocalRouter) CloudHSMLocalRouter {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PaginatedCloudHSMClientList
type PaginatedCloudHSMClientList struct {
	Count   int              `json:"Count"`
	From    OptInt           `json:"From"`
	Total   OptInt           `json:"Total"`
	Clients []CloudHSMClient `json:"Clients"`
}

// GetCount returns the value of Count.
func (s *PaginatedCloudHSMClientList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedCloudHSMClientList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedCloudHSMClientList) GetTotal() OptInt {
	return s.Total
}

// GetClients returns the value of Clients.
func (s *PaginatedCloudHSMClientList) GetClients() []CloudHSMClient {
	return s.Clients
}

// SetCount sets the value of Count.
func (s *PaginatedCloudHSMClientList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedCloudHSMClientList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedCloudHSMClientList) SetTotal(val OptInt) {
	s.Total = val
}

// SetClients sets the value of Clients.
func (s *PaginatedCloudHSMClientList) SetClients(val []CloudHSMClient) {
	s.Clients = val
}

// Ref: #/components/schemas/PaginatedCloudHSMList
type PaginatedCloudHSMList struct {
	Count     int        `json:"Count"`
	From      OptInt     `json:"From"`
	Total     OptInt     `json:"Total"`
	CloudHSMs []CloudHSM `json:"CloudHSMs"`
}

// GetCount returns the value of Count.
func (s *PaginatedCloudHSMList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedCloudHSMList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedCloudHSMList) GetTotal() OptInt {
	return s.Total
}

// GetCloudHSMs returns the value of CloudHSMs.
func (s *PaginatedCloudHSMList) GetCloudHSMs() []CloudHSM {
	return s.CloudHSMs
}

// SetCount sets the value of Count.
func (s *PaginatedCloudHSMList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedCloudHSMList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedCloudHSMList) SetTotal(val OptInt) {
	s.Total = val
}

// SetCloudHSMs sets the value of CloudHSMs.
func (s *PaginatedCloudHSMList) SetCloudHSMs(val []CloudHSM) {
	s.CloudHSMs = val
}

// Ref: #/components/schemas/PaginatedCloudHSMSoftwareLicenseList
type PaginatedCloudHSMSoftwareLicenseList struct {
	Count     int                       `json:"Count"`
	From      OptInt                    `json:"From"`
	Total     OptInt                    `json:"Total"`
	CloudHSMs []CloudHSMSoftwareLicense `json:"CloudHSMs"`
}

// GetCount returns the value of Count.
func (s *PaginatedCloudHSMSoftwareLicenseList) GetCount() int {
	return s.Count
}

// GetFrom returns the value of From.
func (s *PaginatedCloudHSMSoftwareLicenseList) GetFrom() OptInt {
	return s.From
}

// GetTotal returns the value of Total.
func (s *PaginatedCloudHSMSoftwareLicenseList) GetTotal() OptInt {
	return s.Total
}

// GetCloudHSMs returns the value of CloudHSMs.
func (s *PaginatedCloudHSMSoftwareLicenseList) GetCloudHSMs() []CloudHSMSoftwareLicense {
	return s.CloudHSMs
}

// SetCount sets the value of Count.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetCount(val int) {
	s.Count = val
}

// SetFrom sets the value of From.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetFrom(val OptInt) {
	s.From = val
}

// SetTotal sets the value of Total.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetTotal(val OptInt) {
	s.Total = val
}

// SetCloudHSMs sets the value of CloudHSMs.
func (s *PaginatedCloudHSMSoftwareLicenseList) SetCloudHSMs(val []CloudHSMSoftwareLicense) {
	s.CloudHSMs = val
}

// * `cloud/cloudhsm/partition` - Type-L7.
// Ref: #/components/schemas/ServiceClassEnum
type ServiceClassEnum string

const (
	ServiceClassEnumCloudCloudhsmPartition ServiceClassEnum = "cloud/cloudhsm/partition"
)

// AllValues returns all ServiceClassEnum values.
func (ServiceClassEnum) AllValues() []ServiceClassEnum {
	return []ServiceClassEnum{
		ServiceClassEnumCloudCloudhsmPartition,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ServiceClassEnum) MarshalText() ([]byte, error) {
	switch s {
	case ServiceClassEnumCloudCloudhsmPartition:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ServiceClassEnum) UnmarshalText(data []byte) error {
	switch ServiceClassEnum(data) {
	case ServiceClassEnumCloudCloudhsmPartition:
		*s = ServiceClassEnumCloudCloudhsmPartition
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/WrappedCloudHSM
type WrappedCloudHSM struct {
	CloudHSM CloudHSM `json:"CloudHSM"`
}

// GetCloudHSM returns the value of CloudHSM.
func (s *WrappedCloudHSM) GetCloudHSM() CloudHSM {
	return s.CloudHSM
}

// SetCloudHSM sets the value of CloudHSM.
func (s *WrappedCloudHSM) SetCloudHSM(val CloudHSM) {
	s.CloudHSM = val
}

// Ref: #/components/schemas/WrappedCloudHSMClient
type WrappedCloudHSMClient struct {
	Client CloudHSMClient `json:"Client"`
}

// GetClient returns the value of Client.
func (s *WrappedCloudHSMClient) GetClient() CloudHSMClient {
	return s.Client
}

// SetClient sets the value of Client.
func (s *WrappedCloudHSMClient) SetClient(val CloudHSMClient) {
	s.Client = val
}

// Ref: #/components/schemas/WrappedCloudHSMPeer
type WrappedCloudHSMPeer struct {
	Peer CloudHSMPeer `json:"Peer"`
}

// GetPeer returns the value of Peer.
func (s *WrappedCloudHSMPeer) GetPeer() CloudHSMPeer {
	return s.Peer
}

// SetPeer sets the value of Peer.
func (s *WrappedCloudHSMPeer) SetPeer(val CloudHSMPeer) {
	s.Peer = val
}

// Ref: #/components/schemas/WrappedCloudHSMSoftwareLicense
type WrappedCloudHSMSoftwareLicense struct {
	CloudHSM CloudHSMSoftwareLicense `json:"CloudHSM"`
}

// GetCloudHSM returns the value of CloudHSM.
func (s *WrappedCloudHSMSoftwareLicense) GetCloudHSM() CloudHSMSoftwareLicense {
	return s.CloudHSM
}

// SetCloudHSM sets the value of CloudHSM.
func (s *WrappedCloudHSMSoftwareLicense) SetCloudHSM(val CloudHSMSoftwareLicense) {
	s.CloudHSM = val
}

// Ref: #/components/schemas/WrappedCreateCloudHSM
type WrappedCreateCloudHSM struct {
	CloudHSM CreateCloudHSM `json:"CloudHSM"`
}

// GetCloudHSM returns the value of CloudHSM.
func (s *WrappedCreateCloudHSM) GetCloudHSM() CreateCloudHSM {
	return s.CloudHSM
}

// SetCloudHSM sets the value of CloudHSM.
func (s *WrappedCreateCloudHSM) SetCloudHSM(val CreateCloudHSM) {
	s.CloudHSM = val
}

// Ref: #/components/schemas/WrappedCreateCloudHSMClient
type WrappedCreateCloudHSMClient struct {
	Client CreateCloudHSMClient `json:"Client"`
}

// GetClient returns the value of Client.
func (s *WrappedCreateCloudHSMClient) GetClient() CreateCloudHSMClient {
	return s.Client
}

// SetClient sets the value of Client.
func (s *WrappedCreateCloudHSMClient) SetClient(val CreateCloudHSMClient) {
	s.Client = val
}

// Ref: #/components/schemas/WrappedCreateCloudHSMPeer
type WrappedCreateCloudHSMPeer struct {
	Peer CreateCloudHSMPeer `json:"Peer"`
}

// GetPeer returns the value of Peer.
func (s *WrappedCreateCloudHSMPeer) GetPeer() CreateCloudHSMPeer {
	return s.Peer
}

// SetPeer sets the value of Peer.
func (s *WrappedCreateCloudHSMPeer) SetPeer(val CreateCloudHSMPeer) {
	s.Peer = val
}

// Ref: #/components/schemas/WrappedCreateCloudHSMSoftwareLicense
type WrappedCreateCloudHSMSoftwareLicense struct {
	CloudHSM CreateCloudHSMSoftwareLicense `json:"CloudHSM"`
}

// GetCloudHSM returns the value of CloudHSM.
func (s *WrappedCreateCloudHSMSoftwareLicense) GetCloudHSM() CreateCloudHSMSoftwareLicense {
	return s.CloudHSM
}

// SetCloudHSM sets the value of CloudHSM.
func (s *WrappedCreateCloudHSMSoftwareLicense) SetCloudHSM(val CreateCloudHSMSoftwareLicense) {
	s.CloudHSM = val
}
