// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CloudhsmCloudhsmsClientsCreateOperation    OperationName = "CloudhsmCloudhsmsClientsCreate"
	CloudhsmCloudhsmsClientsDestroyOperation   OperationName = "CloudhsmCloudhsmsClientsDestroy"
	CloudhsmCloudhsmsClientsListOperation      OperationName = "CloudhsmCloudhsmsClientsList"
	CloudhsmCloudhsmsClientsRetrieveOperation  OperationName = "CloudhsmCloudhsmsClientsRetrieve"
	CloudhsmCloudhsmsClientsUpdateOperation    OperationName = "CloudhsmCloudhsmsClientsUpdate"
	CloudhsmCloudhsmsCreateOperation           OperationName = "CloudhsmCloudhsmsCreate"
	CloudhsmCloudhsmsDestroyOperation          OperationName = "CloudhsmCloudhsmsDestroy"
	CloudhsmCloudhsmsListOperation             OperationName = "CloudhsmCloudhsmsList"
	CloudhsmCloudhsmsPeersCreateOperation      OperationName = "CloudhsmCloudhsmsPeersCreate"
	CloudhsmCloudhsmsPeersDestroyOperation     OperationName = "CloudhsmCloudhsmsPeersDestroy"
	CloudhsmCloudhsmsPeersRetrieveOperation    OperationName = "CloudhsmCloudhsmsPeersRetrieve"
	CloudhsmCloudhsmsRetrieveOperation         OperationName = "CloudhsmCloudhsmsRetrieve"
	CloudhsmCloudhsmsUpdateOperation           OperationName = "CloudhsmCloudhsmsUpdate"
	CloudhsmLicensesCreateOperation            OperationName = "CloudhsmLicensesCreate"
	CloudhsmLicensesDestroyOperation           OperationName = "CloudhsmLicensesDestroy"
	CloudhsmLicensesListOperation              OperationName = "CloudhsmLicensesList"
	CloudhsmLicensesRetrieveOperation          OperationName = "CloudhsmLicensesRetrieve"
	CloudhsmLicensesUpdateOperation            OperationName = "CloudhsmLicensesUpdate"
	KmsKeysCreateOperation                     OperationName = "KmsKeysCreate"
	KmsKeysDecryptOperation                    OperationName = "KmsKeysDecrypt"
	KmsKeysDestroyOperation                    OperationName = "KmsKeysDestroy"
	KmsKeysEncryptOperation                    OperationName = "KmsKeysEncrypt"
	KmsKeysListOperation                       OperationName = "KmsKeysList"
	KmsKeysRetrieveOperation                   OperationName = "KmsKeysRetrieve"
	KmsKeysRotateOperation                     OperationName = "KmsKeysRotate"
	KmsKeysScheduleDestructionOperation        OperationName = "KmsKeysScheduleDestruction"
	KmsKeysStatusOperation                     OperationName = "KmsKeysStatus"
	KmsKeysUpdateOperation                     OperationName = "KmsKeysUpdate"
	SecretmanagerVaultsCreateOperation         OperationName = "SecretmanagerVaultsCreate"
	SecretmanagerVaultsDestroyOperation        OperationName = "SecretmanagerVaultsDestroy"
	SecretmanagerVaultsListOperation           OperationName = "SecretmanagerVaultsList"
	SecretmanagerVaultsRetrieveOperation       OperationName = "SecretmanagerVaultsRetrieve"
	SecretmanagerVaultsSecretsCreateOperation  OperationName = "SecretmanagerVaultsSecretsCreate"
	SecretmanagerVaultsSecretsDestroyOperation OperationName = "SecretmanagerVaultsSecretsDestroy"
	SecretmanagerVaultsSecretsListOperation    OperationName = "SecretmanagerVaultsSecretsList"
	SecretmanagerVaultsSecretsUnveilOperation  OperationName = "SecretmanagerVaultsSecretsUnveil"
	SecretmanagerVaultsUpdateOperation         OperationName = "SecretmanagerVaultsUpdate"
)
